### ISSUE TITLE
Initialise `mojs` instance only after the `DOMContentLoaded`

### ISSUE THREAD

**Issue by legomushroom** [mojs/mojs#103]
This will ensure that autogenerated modules like `Shape` are not broke if you link the `mojs` script to the `<head>`.

Something like this should do:

```javascript
const doc = document;
const docState = doc.readyState;
if (docState === "complete" || docState === "loaded"  || docState === "interactive") {
  // initialisation
}

doc.addEventListener('DOMContentLoaded', () => {   /* initialisation */ });
```

**Comment by indolering** [comment]
```
const doc = document;
const docState = doc.readyState;
if (docState === "complete" || docState === "loaded"  || docState === "interactive") {
  // initialisation
}
```

Is this for the sake of backwards compatibility?  You have to go all the way [back to IE8](https://caniuse.com/#search=DOMContentLoaded) to find an incompatible browser.  JQuery [dropped support for IE8](https://blog.jquery.com/2013/04/18/jquery-2-0-released/) back in 2013....

**Comment by indolering** [comment]
> Is this for the sake of backwards compatibility?

Derp, no it's to check if `domContentLoaded` has already been called*.

That being said, I'm not sure how to fit this into v2.  Everything is an ES6 module (which solves the loading/dependency resolution step) and the build process has too much magic for me to contribute 😊 .

\*_\<grumble\>God forbid the JS standards committee gives us an idiot proof, boilerplate API for common tasks.\<grumble\/\>_

**Comment by xavierfoucrier** [comment]
It is not recommended to put scripts inside the head tag, especially third party libraries like `mojs` that need the DOM to properly work. It can be considered as "render blocking resources" by Google if you don't defer it too.

Using a **bundler** like webpack and put the minified bundle before closing the `<body>` tag looks the best solution.

In addition, most developers will have to rely on DOMContentLoaded event, like for preload stuff, when working with JS modules. It is better to let them manage this the way they want.
