### ISSUE TITLE
React doesn't work.

### ISSUE THREAD

**Issue by lannex** [mojs/mojs#107]
Hi.

I'm using React and ES2015.
However, if I don't use 'transition' in the style, the animation didn't work.
It activated only start part and end part.
What should i do ?

Thank you for developing cool package anyway!.

**Comment by legomushroom** [comment]
Hi @lannex!

Sorry about that. Could you please make a small demo with the issue so it will be more clear for me.  Thank you!

**Comment by lannex** [comment]
Ok.
My case.

```js
<div 
  onMouseEnter={() => {
    new mojs.Html({
      el: this.hoverItem,
      width: { width: hoverWidth },
    });
  }}
  onMouseLeave={() => {
    new mojs.Html({
      el: this.hoverItem,
      width: { hoverWidth: width },
    });
  }}
/>
```

even 'Tween'.

**Comment by legomushroom** [comment]
Hi @lannex!

Thanks for the samples, sorry for the delayed response. What is the `this.hoverItem` in your samples and what is the second sample about? You are trying to make animation that expands some div on hover and shrinks when hover state released?

**Comment by lannex** [comment]
Oh. It's wrong code. not `this.hoverItem` but `this.item`.Sorry.
and 
Yes. i'm trying to make hover animation.

**Comment by xavierfoucrier** [comment]
Hi @lannex,

Did this issue is fixed today?
Thx

**Comment by lannex** [comment]
Hi @xavierfoucrier 
It was my mistake.
