### ISSUE TITLE
Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by evejweinberg** [mojs/mojs#110]
Not sure what this issue is, but I was just trying to run the first Shape example, and keep getting the error copy/pasted below. Here is a simple gist of my code: https://gist.github.com/evejweinberg/427d636080c730fc890da7e31538ed5e

ERROR: 

Uncaught TypeError: Cannot read property 'appendChild' of null
    at Helpers.vars (mo2.js:6886)
    at new Helpers (mo2.js:6866)
    at Object.<anonymous> (mo2.js:7519)
    at __webpack_require__ (mo2.js:30)
    at Object.<anonymous> (mo2.js:10463)
    at Object.<anonymous> (mo2.js:10607)
    at __webpack_require__ (mo2.js:30)
    at Object.<anonymous> (mo2.js:57)
    at __webpack_require__ (mo2.js:30)
    at mo2.js:50
Helpers.vars @ mo2.js:6886
Helpers @ mo2.js:6866
(anonymous) @ mo2.js:7519
__webpack_require__ @ mo2.js:30
(anonymous) @ mo2.js:10463
(anonymous) @ mo2.js:10607
__webpack_require__ @ mo2.js:30
(anonymous) @ mo2.js:57
__webpack_require__ @ mo2.js:30
(anonymous) @ mo2.js:50
(anonymous) @ mo2.js:53
webpackUniversalModuleDefinition @ mo2.js:9
(anonymous) @ mo2.js:10
test1.html:28 ready
test1.html:32 Uncaught ReferenceError: mojs is not defined
    at HTMLDocument.<anonymous> (test1.html:32)

**Comment by legomushroom** [comment]
Hi Eve,

Sorry about that and thanks for the issue. Just send the script with `mojs` reference somewhere inside `<body>` tag instead of `<head>` - there is the issue that will be solved in near future, but for now, you need to link `mojs` inside body tag.

Cheers!

**Comment by indolering** [comment]
Adding a `defer` and triggering your scripts after the `DOMContentLoaded` event fixed the issue for me.

**Comment by rahulgit** [comment]
thinks @legomushroom  that works ...
