### ISSUE TITLE
Opacity parameter on HTML

### ISSUE THREAD

**Issue by kujohn** [mojs/mojs#119]
The opacity parameter doesn't seem to transition for HTML Modules.

**Comment by mateobadillo** [comment]
Had the same problem, it's because the syntax is different, something like this should solve your issue:
`var tween = new mojs.Tween({
                        repeat: 1,
                        duration: 200,
                        onProgress: function(progress) {
                            element.style.opacity = progress;
                        }
                    });`

**Comment by legomushroom** [comment]
Can you guys provide me with an example? Thanks!

**Comment by zbrukas** [comment]
If you use the example on codepen and add opacity
```js
const html = new mojs.Html({
  // selector for HTMLElement
  el: '#js-el',
  opacity: 0,
  // animate translateX from 0 to 200 pixels
  // each delta object can have entire set of tween properties and callbacks
  x: { 0: -200, duration: 1000, delay: 200, easing: 'cubic.out', onComplete () { console.log('x property animation complete') } },
  y: { 0: -200, duration: 2000, onComplete () { console.log('y property animation complete') } },
  // static properties
  left: '50%',
  top:  '50%'
});
```
the div doesn't change the opacity.

**Comment by legomushroom** [comment]
@zbrukas thanks for your feedback and the code sample. This will be fixed in the nearest `mojs@2` release.
If you stuck currently, you can just set opacity as `null-delta`:

```javascript
const html = new mojs.Html({
  // selector for HTMLElement
  el: '#js-el',
  opacity: { 0: 0 },
  // animate translateX from 0 to 200 pixels
  // each delta object can have entire set of tween properties and callbacks
  x: { 0: -200, duration: 1000, delay: 200, easing: 'cubic.out', onComplete () { console.log('x property animation complete') } },
  y: { 0: -200, duration: 2000, onComplete () { console.log('y property animation complete') } },
  // static properties
  left: '50%',
  top:  '50%'
});
```

Or just set the style directly on the element:

```javascript
html.el.style.opacity = 0;
```

Let me know!

**Comment by zbrukas** [comment]
@legomushroom I did the trick mentioned above

```js
const html = new mojs.Tween({
      delay: 1000,
      duration: 500,
      onProgress: (progress) => {
        title.style.opacity = progress;
      }
    });
```
Only the delay doesn't seem to delay much, but works for the moment 😄 I'd love to contribute, but vector sciences are a little beyond me 😞

**Comment by legomushroom** [comment]
@zbrukas oh you want to animate the opacity?

Then you can do:

```javascript
const html = new mojs.Html({
  // selector for HTMLElement
  el: '#js-el',
  opacity: { 0: 1 },
  delay: 1000,
  duration: 500,
  // static properties
  left: '50%',
  top:  '50%'
}).play();
```
As you can see, `mojs` use `{ start: end }` syntax for that to decribe transitions on properties. [demo](https://codepen.io/sol0mka/pen/YxyoLL?editors=0010)

If you want to do it in the `tween` fashion, just use the `onUpdate` instead of `onProgress`, because `onProgress` is the callback that does not respect `delay`:

```
const html = new mojs.Tween({
      delay: 1000,
      duration: 500,
      onUpdate: (easedProgress, progress) => {
        title.style.opacity = easedProgress;
      }
});
```

Alos, if you want to contribute, I have a lot of tasks that don't involve any vector science ;)

**Comment by zbrukas** [comment]
Works perfectly. Now back to understand the config on the demos 😆

**Comment by legomushroom** [comment]
@zbrukas happy to help, let me know!

**Comment by zbrukas** [comment]
@legomushroom basically I wanted to adapt the dust example on the examples page, but using a bigger svg image. Now I can't make the bubbles have the same effect as the example, they're too far up. But best if I delete this comment and we talk though other channel? Or gitter?

**Comment by legomushroom** [comment]
@zbrukas no need to delete, someone can find a solution to the problem when reading this. Just open another issue here on Github. If you want to do it secretly, I can invite you to slack channel.

**Comment by legomushroom** [comment]
@zbrukas sent you the invite, please check the email listed in your GitHub account.
