### ISSUE TITLE
HTML5 Canvas support

### ISSUE THREAD

**Issue by vincentchambray** [mojs/mojs#121]
Hi legomushroom,
Fantastic work on mojs.

Do you know when we can expect to create these animations inside a HTML5 Canvas? I've seen comments from you on this coming soon, but not sure on the timeline?

Thanks and again nice work!

**Comment by elliottregan** [comment]
Is there any reason we would want to support Canvas?

**Comment by vincentchambray** [comment]
It would open mo.js into working with game developers who use HTML5 Canvas. There's a huge market of developers who could benefit from the work by adding easy to create motion graphics into their HTML5 games.

**Comment by elliottregan** [comment]
Ahh that makes sense.

**Comment by legomushroom** [comment]
@vincentchambray @elliottregan canvas support is planned but not ready yet.

**Comment by kumarharsh** [comment]
+1, although @legomushroom I must say - this is an ***amazing*** library - I never thought I'd see something like this in my lifetime 😆. Thoroughly impressed with the simplicity, and the performance aspects too! For a while I was under the impression that this was a *canvas-only* library - turns out it was doing DOM manipulations!

**Comment by legomushroom** [comment]
@kumarharsh thanks! Yeah, it uses SVG under the hood. Just out of interest, what modules do you use most? Working on the `mojs2` at the moment and your feedback can help me to make right decisions :) Thanks a lot!

**Comment by kumarharsh** [comment]
I'm just exploring the library right now and working out how to yse this with react, would start using it soon in a project of mine. I'll start giving feedback once I get to that stage. One piece of feedback currently I have is that the website tutorials don't showcase stagger, etc. But I see that you're busy with the next iteration, so I guess that can be done later!

**Comment by legomushroom** [comment]
@kumarharsh great, let me know if you have any questions or feedback!

**Comment by danvoyce** [comment]
Would love to see canvas / webgl support!
