### ISSUE TITLE
How can I add multiple animations to the same shape? Also, chain animations one after the another on multiple objects? 

### ISSUE THREAD

**Issue by ishaaniMittal** [mojs/mojs#127]
Hi, As shown in this pen - http://codepen.io/sol0mka/pen/bbd4fe6c1ac8519c76bc18828844e2c3
are three different animations on three different shapes. I want to add these three animations, one after the another on the same object. Is that possible? 
When I tried tuning the x cordinates after play, the code didn't work. 

const rect = new mojs.Shape({
  shape:  			'rect',
  left:         '50%',
  fill:         'none',
  radius:       20,
  stroke:        'rgba(0,255,255, 1)' ,
  strokeWidth: 4,
  angle:        { 0: 180 },
  delay:2000,
  duration:     2000,
  repeat:999,
  onComplete(){
    rect.tune({x:{0:'100%'}})
  }
}).play();

the above piece of code doesn't work. 

const rect = new mojs.Shape({
  shape:  			'rect',
  left:         '50%',
  fill:         'none',
  radius:       20,
  stroke:        'rgba(0,255,255, 1)' ,
  strokeWidth: 4,
  angle:        { 0: 180 },
  delay:2000,
  duration:     2000
 
}).play();

rect.tune({x:{0:'100%'}});

When I tried using this piece of code, the animations are not run in sequence but becomes one. Please advice what should be done! 
I am also looking to chain animations on different objects one after the another. A rudimentary solution is to calculate time of each animation and add a delay component in subsequent animations, but I am sure there must be a much more elegant way to do this. Kindly share some simple examples. 

 const circle = new mojs.Shape({
  shape:  			'circle',
  scale:   			{ 0 : 1 },
  left:         '25%',
  fill:         { 'cyan': 'yellow' },
  radius:       25,
  
  duration:     2000
});
 

const rect = new mojs.Shape({
  shape:  			'rect',
  left:         '50%',
  fill:         'none',
  radius:       20,
  stroke:        'rgba(0,255,255, 1)' ,
  strokeWidth: 4,
  angle:        { 0: 180 },
  delay:2000,
  duration:     2000
 
}).play();

const polygon = new mojs.Shape({
  shape:  			'rect',
  points:       4,
  left:         '75%',
  fill:         { 'deeppink' : '#00F87F' },
  x:            { 'rand(-100%, -200%)' : 0  },
  angle:        { 0: 122 },
  radius:       25,
  delay:4000,
  duration:     2000
});

var timelineTrue = new mojs.Timeline();
timelineTrue.add(circle,rect,polygon);

timelineTrue.play(); 

The examples given on the website are too complicated to understand.

**Comment by gaou-piou** [comment]
Try something like this
`
const shape = new mojs.Shape({
  shape: 'rect',
  left: '50%',
  fill: 'none',
  radius: 20,
  stroke: 'rgba(0,255,255, 1)' ,
  strokeWidth: 4,
  isShowStart: true,
});
const rect = new mojs.Html({
  el: shape.el,
  angleZ: { 0: 90, duration: 1000},
  x: {0:"100%", delay: 1000, duration: 1000},
});
new mojs.Timeline({repeat: 999, yoyo: true}).add(rect).play()
`
