### ISSUE TITLE
Multiple Codepen demos have syntax errors and do not work.

### ISSUE THREAD

**Issue by knpwrs** [mojs/mojs#128]
The syntax errors each unveil other syntax errors. I think the best course of action is to rebuild the demos and paste them back into codepen.

The demos which are broken:

* [Mograph](http://codepen.io/sol0mka/full/39427561a8a0b15d7896480a7d96d3d1/)
* [Physical Balls](http://codepen.io/sol0mka/full/7315f4364360ec87a6655d33782702fe/)

**Comment by knpwrs** [comment]
Here's a partially working demo of the first example (or, at least what is linked from codepen) on WebpackBin: https://www.webpackbin.com/bins/-KgXE3zcyZTeeNXZ3fad

**Comment by legomushroom** [comment]
Hi Ken!

Thanks for the heads up, will try to fix it asap.
