### ISSUE TITLE
Tutorials are not clickable

### ISSUE THREAD

**Issue by samtstern** [mojs/mojs#13]
In the Tutorials sidebar of mojs.io I can only click `Path Easing`, all others are unclickable.  This is true on Chrome for Mac and Linux as well as Edge on Windows.
![screenshot from 2015-11-23 08 38 13](https://cloud.githubusercontent.com/assets/8466666/11342724/a27a45d0-91bd-11e5-84bf-6567f3665794.png)

**Comment by legomushroom** [comment]
Hi @samtstern ! Thanks for the issue.

I'm sorry about that. Unfortunately this is intended behaviour - there is `only one` tutorial available to public right now. Probably I should make the disabled links more obscured or add `[soon]` labels to soften the confusion.

`mo · js` is under active development, the reason for the early release was -- a try to appeal community's interest thus some free hands to help me to implement everything I have had planned. I'm building it on my own besides my full time job so I really need the help. I'm sorry if you feel frustrated right now and thanks for understanding.

Cheers

**Comment by samtstern** [comment]
Ah that makes sense.  Well the one tutorial that currently exists is amazing, makes me excited for the rest.

**Comment by legomushroom** [comment]
Let's keep the issue open, we will have more confused users I believe.

**Comment by prateekjadhwani** [comment]
@legomushroom do you have any deadline on the docs?

**Comment by eebann** [comment]
ur work is great.. better explanation should be made when theres any new update

**Comment by Randore** [comment]
How soon can we expect the tutorials, eagerly waiting to follow tutorials and use in our projects.

**Comment by legomushroom** [comment]
@Randore very soon!

**Comment by karneaud** [comment]
+1

**Comment by rickli1989** [comment]
+1

**Comment by legomushroom** [comment]
New tutorials are ready! Should be live as soon as somebody will proofread them for me.

**Comment by rickli1989** [comment]
Awesome

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.12.43&pv=9.2.1&source=email_footer_2]
On Fri, Jul 15, 2016 at 9:46 AM, Oleg Solomka <notifications@github.com> wrote:
New tutorials are ready! Should be live as soon as somebody will proofread them for me.

**Comment by legomushroom** [comment]
Any native english speaker what's to help me with it?

**Comment by stereojam** [comment]
I can help

On Thu, Jul 14, 2016 at 19:49, Oleg Solomka <notifications@github.com> wrote:
Any native english speaker what's to help me with it?

**Comment by legomushroom** [comment]
@stereojam nice! Please shoot me your email here or to [legomushroom@gmail.com](mailto:legomushroom@gmail.com).

**Comment by legomushroom** [comment]
@stereojam actually I've found one in your profile, can I use it for slack?

**Comment by stereojam** [comment]
email? hihi@stereoj.am

On Thu, Jul 14, 2016 at 20:03, Oleg Solomka <notifications@github.com> wrote:
@stereojam [https://github.com/stereojam] actually I've found one in your profile, can I use it for slack?

**Comment by eshansingh** [comment]
@legomushroom Sorry for being so pesky, but it's been 20 days. If you have any trouble, I'd be happy to help. Shoot me an email at eshansingh@gmail.com

**Comment by legomushroom** [comment]
@eshansingh what do you mean?

**Comment by eebann** [comment]
eban.emmanuel@@gmail.com all ready to help if u need more hands
