### ISSUE TITLE
Can't using "Mo-js" in framework7 :confused:

### ISSUE THREAD

**Issue by cuduy197** [mojs/mojs#130]
Thank @eltonmesquita 
Edit: to fix it you need  add z-index: 0 to the app container style; 
ex: 
`* {
 z-index: 0
}`

Problem: 
I can't using http://mojs.io/ in framework7 :disappointed: 
I dont know why? :confused: 
Pleace help me. :face_with_head_bandage:  

Anybody using mo.js with framework7?

**Comment by legomushroom** [comment]
Hi @cuduy197! 

Could you give me more info for the issue? Do you see any error?

**Comment by cuduy197** [comment]
Nothing error when I import mo-is in <body> 
but mo-js does work on my app (using framework7 with vue + webpack2) ? 

`    document.addEventListener('click', function(e) {
      const coords = {
        x: e.pageX,
        y: e.pageY
      };
      burst
        .tune(coords)
        .replay();
    });`

**Comment by legomushroom** [comment]
Thanks for the information. It is hard to say what's wrong right now. If you can create a simple demo on `CodePen` or `JsBin` would be great.

**Comment by eltonmesquita** [comment]
@cuduy197, mo.js works ok with Vue.js (so it should work ok with Framework7 too). Here a [simple port of an example](http://codepen.io/eltonmesquita/pen/gmJdKP) from the tutorials ported to Vue.js.

Use Vue.js events (like: `<button @click="yourMethod"></button>`. Vue.js is data-driven, so it's better to think in the Vue's way when porting mo.js code to an app. Better start with something simple like porting an tutorial's example to Vue.js.

**Comment by legomushroom** [comment]
@eltonmesquita nice one! So it definitely works with `Vue.js` wondering what's up with `Framework7`.

**Comment by cuduy197** [comment]
@eltonmesquita did you try with Framework7 ? 
I add mo-js like you in component, but :confused:  not thing happened ?

**Comment by eltonmesquita** [comment]
Thanks!
I'll have to try it with framework 7 but it should work as it's running inside a webview. I'll look at it later.

**Comment by eltonmesquita** [comment]
@cuduy197 was right, nothing is shown when running mojs in framework7. But it's a simple z-index issue. I don't know why, but the app always overlays the mojs elements. The simple fix is to just add `z-index: 0` to the app container and everything works as it should. Hope it solves your issues @cuduy197 .

**Comment by legomushroom** [comment]
Awesome, this makes sense. You can have access to the DOM element of the Burst (`burst.el`) so can increase `zIndex` by:

```
burst.el.style.zIndex = 2;
```

Should work just fine. Thanks for your help @eltonmesquita!

**Comment by eltonmesquita** [comment]
Glad I can help @legomushroom!
Weirdly enough increasing the mojs element `z-index`makes no difference, even though there's no z-index on the app div and mojs elements are added after the app element. The only fix seems to be declaring a low `z-index` directly to the app element.

It makes no sense to me as this shouldn't happen. Maybe it's a webview issue? Or something related to transform/Css 3d context and Safari Mobile?

**Comment by legomushroom** [comment]
Humm, that's strange, are you setting it in `dev tools` or can you confirm that it is set in `dev tools`?

**Comment by eltonmesquita** [comment]
Tried both and the results are the same, the elements still get under the app container. I'm trying to run this on Android, but it's a bit trickier than iOS.

**Comment by cuduy197** [comment]
@eltonmesquita Thanks you so much, but where to add `z-index: 0` ? 
Can you give me example ?

**Comment by cuduy197** [comment]
`burst.el.style.zIndex = 99999; `
WILL FIX THIX :tada:
