### ISSUE TITLE
mojs.Burst is not a constructor

### ISSUE THREAD

**Issue by Bobsans** [mojs/mojs#133]
Error in builded script.
<img src="https://2.downloader.disk.yandex.ru/disk/831d8f68ad39b4088240dd57b167fe52860e9eec93572485087b456e84a60153/59034caf/CJqpd-2b7k3kgg60yI-6udB2jkSnqtYSoa0EZi1TQtxHpV_k8xdu368Hs_V-ASwE8s0ZR6U2F2jCWXD7V9jdaw%3D%3D?uid=0&filename=2017-04-28_13-06-21.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=6561&hid=56167a01fc53edd5c67a5b8fe172e5a2&media_type=image&tknv=v2&etag=4542cb958bff344b2e69e6455660d7e3">

**Comment by legomushroom** [comment]
Hey Bobsans,

Thanks for the issue, could you give me more info on this?

**Comment by ellkell** [comment]
Hi!

Also getting a `mojs.Burst is not a constructor` error when using the **mo.min.js** file in the current build.  The CDN version of **mo.min.js** works though.  Let me know if you need anymore info, cheers!

**Comment by legomushroom** [comment]
Hi Laura,

Thanks for submitting this. You mean it is broken when using the `mo.min.js` from the git repo?

**Comment by Bobsans** [comment]
Hi!
Thanks Laura. 
On using current `mo.min.js` or `mo.js` from this repository not working anything.

```
Uncaught TypeError: Cannot read property 'appendChild' of null
    at t.vars (mo.min.js:7)
    at new t (mo.min.js:7)
    at Object.<anonymous> (mo.min.js:7)
    at e (mo.min.js:7)
    at Object.<anonymous> (mo.min.js:7)
    at Object.t.exports.t.webpackPolyfill.t.deprecate (mo.min.js:7)
    at e (mo.min.js:7)
    at Object.e.__esModule (mo.min.js:7)
    at e (mo.min.js:7)
    at mo.min.js:7

i.html:65 Uncaught ReferenceError: mojs is not defined
    at index.html:65
```

**Comment by legomushroom** [comment]
Seems like the repo has broken build, please use this one of these:

```shell
npm: npm install mo-js

cdn: <script src="//cdn.jsdelivr.net/mojs/latest/mo.min.js"></script>

bower: bower install mojs
```

@Bobsans try to link the `mojs` file inside `document.body` or use [DOMCOntentLoaded](https://developer.mozilla.org/ru/docs/Web/Events/DOMContentLoaded) event to make sure the `mojs` source loaded before using it.

**Comment by DanielRuf** [comment]
Getting `ReferenceError: Burst is not defined`

**Comment by DanielRuf** [comment]
Should be `new mojs.Burst`
