### ISSUE TITLE
Why auto-run a circle animation with default ?

### ISSUE THREAD

**Issue by NumerHero** [mojs/mojs#136]
I just load upcompressed mo.js, and mojs auto-draw a circle and let it animate.

The code as follow

![image](https://cloud.githubusercontent.com/assets/12696061/25858423/493a15ae-350e-11e7-8783-cb090956df70.png)

**Comment by legomushroom** [comment]
Hey @NumerHero!

Thanks for the issue, I'm not sure I'm following, what was the question?

**Comment by NumerHero** [comment]
I think you may forget note your test code. There result will make a circle animation when i load the mo.js

**Comment by legomushroom** [comment]
@NumerHero oh you mean I left it in the bundle? what is the version of `mojs` do you use and where did you get it?

**Comment by NumerHero** [comment]
Yes, and the mojs version was 0.288.1
