### ISSUE TITLE
Wrapper div and SVG having wrong dimension

### ISSUE THREAD

**Issue by shelune** [mojs/mojs#153]
I'm importing my custom shape and making it rotate. However it rotates the wrong way, with the containing div being much bigger than the shape itself. How can correct this?

This is the pen: https://codepen.io/shelune/pen/veYMRa

![screen shot 2017-09-13 at 17 23 07](https://user-images.githubusercontent.com/9392701/30382786-bd28d498-98a8-11e7-8f31-5f8eb52444da.png)

![screen shot 2017-09-13 at 17 23 22](https://user-images.githubusercontent.com/9392701/30382788-bf9703bc-98a8-11e7-970f-831b34d06a62.png)

**Comment by xavierfoucrier** [comment]
I @shelune! Your codepen link doesn't fit to your screenshot, is that normal?

**Comment by shelune** [comment]
Ah sorry @xavierfoucrier I've modified it to another test so...

**Comment by xavierfoucrier** [comment]
Ok. So you don't have the old pen anymore? Or a sample code that highlights your issue?

**Comment by shelune** [comment]
No I've moved on from that.

**Comment by xavierfoucrier** [comment]
Ok no problem!
