### ISSUE TITLE
Tuning/updating mojs.Html object properties after instantiation

### ISSUE THREAD

**Issue by brudoku** [mojs/mojs#156]
Is there any way to change mojs.Html properties like is possible with mojs.Shape using the tune() method? I'd like to reposition mojs.Html elements when the window is resized, I had no problem using shapes but I have nav elements which are HTML and their positions animated with mojs and seem to be stuck. Thanks for any help.

**Comment by danvoyce** [comment]
I'd like to be able to do the same with mojs.Tween. I'd like to update the onUpdate method based on user interaction.

**Comment by xavierfoucrier** [comment]
Hi @brudoku! Since it's an `html` module, you can move the object yourself with css or js by binding the `resize` event of the window. Do you have a sample code that highlights what you want to do exactly?
