### ISSUE TITLE
Quick demo and IE(10,11 and Edge)

### ISSUE THREAD

**Issue by BtM909** [mojs/mojs#16]
The quick demo just stops after 2 seconds with the following error (in the console):

```
SCRIPT5007: Unable to get property 'play' of undefined or null reference
mojs.io (1,4496)
```

The page doesn't render correctly in IE9 mode, but I don't trust the mode-switcher, so just assume it hasn't been tested in IE9. 10, 11 and Edge all stop after 2 seconds.

**Comment by legomushroom** [comment]
Hi @BtM909!

Thanks for the issue.
Looks like there is an error on initialization stage so some properties remain `undefined`.

Investigating :eyeglasses:.
