### ISSUE TITLE
Cleanup repository

### ISSUE THREAD

**Issue by DanielRuf** [mojs/mojs#162]
There is a pack file of 134 megabytes. I'm currently looking where this comes from.
Checking the repository with https://rtyley.github.io/bfg-repo-cleaner/ might be a good idea.

**Comment by Sandstedt** [comment]
Wanna try and see if it helps?

**Comment by DanielRuf** [comment]
Well, you can / should not rewrite the history of the affected branch which would invalidate all forks and PRs.

**Comment by xavierfoucrier** [comment]
Hi @DanielRuf,

Is this still an issue on the `prepublish` branch?
I have never use the BFG tool, so I don't know what can be the impact on the current repository...

Thanks for your clarification. :+1:

**Comment by DanielRuf** [comment]
> Well, you can / should not rewrite the history of the affected branch which would invalidate all forks and PRs.

Probably not. The history of the branch is just too big. Closing for now.
