### ISSUE TITLE
Use encrypted token for TravisCI

### ISSUE THREAD

**Issue by DanielRuf** [mojs/mojs#163]
The `SAUCE_ACCESS_KEY` should be encrypted and also the Slack token.

https://docs.travis-ci.com/user/sauce-connect/

https://docs.travis-ci.com/user/notifications/#Configuring-slack-notifications

It might be a good idea to create new ones, encrypt and add them and revoke access for the old ones.

https://github.com/chaijs/guidelines/blob/master/secure-tokens.md

**Comment by xavierfoucrier** [comment]
Hi @DanielRuf,

Thanks for underlining this :wink: 
It should be OK in the next release, as all CI stuff is under review.

Closing the issue.
