### ISSUE TITLE
Animated shapes remain after fading away but only in Chrome

### ISSUE THREAD

**Issue by ahmed-am** [mojs/mojs#170]
Hi there,
I found this little bug/issue while working on a simple to-do app.

While running it on Firefox, the 'task completed' check animated circles after reaching opacity 0 aren't in DOM anymore, where as in chrome, they remain there and the whole screen because clickable and its causes to press that specific check button.

[Codepen here](https://codepen.io/ahmedam/full/JOmQRz/)

**Comment by xavierfoucrier** [comment]
Codepen demo is broken.
Closing the issue.

**Comment by Sandstedt** [comment]
Just a note in case anyone else read this. If the animation is purely visual, I would suggest always setting `pointer-events: none` to it in CSS. It's cheaper and easier then removing DOM elements (up to a certain limit of course).
