### ISSUE TITLE
Reduce mo.js bundle size

### ISSUE THREAD

**Issue by nicooprat** [mojs/mojs#175]
Hi

I just tried mo.js for the first time to create a simple burst effect on a button. Unfortunately, the size of my app increased a lot:

![capture d ecran 2017-12-29 a 13 19 23](https://user-images.githubusercontent.com/645641/34437022-10a5737e-ec9b-11e7-9de1-14aa632b70de.jpg)

I'm using Webpack 2 from [this template](https://github.com/vuejs-templates/webpack), so I think it should be tree-shaking automatically. Is mo.js compatible? I'm loading it like this:

```js
import {Burst, Timeline} from 'mo-js'
```

Thanks!

**Comment by Frondor** [comment]
Looks like this project is abandoned. Don't waste your time and bloat your bundle.

**Comment by xavierfoucrier** [comment]
Hi @nicooprat,

We are working on making the bundle size smaller for the v1 release.
Tree-shaking should be enable too as we have convert the project to fully use webpack 4 features.

:+1:

**Comment by nicooprat** [comment]
Glad to hear! 🥳
