### ISSUE TITLE
new Burst(...) throws error in React

### ISSUE THREAD

**Issue by TNkemdilim** [mojs/mojs#177]
When trying to use the Burst, it throws the following error.

![image](https://user-images.githubusercontent.com/11903253/34909945-cd5cc46a-f8ab-11e7-8ca2-b20120adc6c1.png)

This is the code sample:
```javascript
var burst = new mojs.Burst({
  parent: like_parent,
  radius: { 30: 40 },
  count: 25,
  angle: { 20: 40 },
  children: {
    delay: 300,
    duration: 900,
    radius: { 10: 0 },
    fill: ['#aaca7e'],
    easing: mojs.easing.bezier(.23, .23, .23, .64)
  }
});
````

**Comment by xavierfoucrier** [comment]
Hi @TNkemdilim!

Seems your code is working fine on my dev environment with `mojs 0.288.2` minified version.

**Comment by Sandstedt** [comment]
@TNkemdilim Hi! Could you send some more info about your project and the bug? Which browser, react version, build systems (babel etc)?

Or if you have time, see if you can reproduce the error in a reduced test case like this: https://codepen.io/sandstedt/pen/xpJdbG
