### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Kaperstone** [mojs/mojs#178]
For some reason I always get this error randomly
![2018-01-16](https://user-images.githubusercontent.com/8384463/34978356-a1a3251a-faa6-11e7-911c-9b1a9dad1835.png)

I have a one page application and I use this library to put some effects to it, I don't always use it, there are places where this library just stands, and wherever I don't use it, it gives me that error, sometimes it takes a lot of time for it to show up, sometimes it shows right after refreshing.

The error is on this line:
```javascript
,t.prototype._restorePlayingTweens=function(){for(var t=0;t<this._savedTweens.length;t++)this._savedTweens[t].resume()},t}()),p=new a;e["default"]=p}
```
for "this._savedTweens.length;"

**Comment by xavierfoucrier** [comment]
Hi @Kaperstone,

Sorry for the long wait.
Did this issue is resolved today?

Thx :wink:

**Comment by Kaperstone** [comment]
I somehow got around this back then, don't remember how.

anyhow, I don't use this lib, this is an amazing lib tho!
