### ISSUE TITLE
Inline-styles, resetting values

### ISSUE THREAD

**Issue by DanielRuf** [mojs/mojs#179]
So far there is no option to not center the shape using negative margins. It would be good to disable this, disable the setting of position: absolute and other things.

Also using a classname, we always have to use `"!important` and thus it is not easy to overwrite the styles with clean CSS.

And the original element is not removed from the DOM. The new generated one should inherit the old one and use its class(es).

**Comment by taykcrane** [comment]
So surprised by this too. @legomushroom any reason why we can't edit the position of the shape? Having to use !important in my CSS to reset things like position:absolute; seems nuts.

**Comment by DanielRuf** [comment]
I guess he is very busy now working at Microsoft so I think it makes sense to create an organization, move the repo to it and add some more maintainers.

**Comment by DanielRuf** [comment]
I guess he is very busy as he is working now at Microsoft so I think it makes sense to create an organization, move the repo to it and add some more maintainers.
