### ISSUE TITLE
How to change the color of the burst?

### ISSUE THREAD

**Issue by olemartin** [mojs/mojs#184]
I don't understand how I can `tune` the stroke variable of the children of a Burst. Please help.

**Comment by xavierfoucrier** [comment]
Hi @olemartin,

It seems that it's not possible to tune burst childrens after initialization.
What effect are you trying to achieve? Do you have some code snippet to show?

Thx

**Comment by olemartin** [comment]
The effect I am trying to achieve is simply to have one component and change color of the burst based on user input

**Comment by xavierfoucrier** [comment]
Ho, cool :+1: 

I think you will need to recreate the burst with his childrens at the moment you want the color to be changed, depending on the use input... but, if you are just using the `children` property to have - for example - both `circle` and `polygon` shapes, you can simply create two burst, play them simultaneously, `tune` them to fit the new colors depending on user input, then `replay` them with no need to recreate the burst.

Sounds clear to you? :smiley: 
If you can show me your `children` usage, I could give you a better answer.

**Comment by xavierfoucrier** [comment]
Hi @olemartin,

In fact, I ended to get it work in a recent project. :smile: 
You can tune `Burst` children by using this syntax:

```js
new mojs.Burst({
  radius: { 0 : 100 },
  count: 20,
  children: {
    shape: 'circle',
    fill: 'black',
    radius: 4,
    duration: 1500
  },
  onComplete: function() {
    this.tune({
      children: { // <-- don't forget to add the sub-object key
        fill: 'blue'
      }
    }).replay();
  }
}).play();
```

Hope this help, several years later :wink:
