### ISSUE TITLE
Ionic and Angular support for this one ?

### ISSUE THREAD

**Issue by AltRoot17** [mojs/mojs#185]
It is support for the Ionic and Angular? how to use it? 
Thanks

**Comment by MikaAK** [comment]
This seems a bit out of scope. Usage with angular would be more of a 
> how do I use outside animations with angular?

```
export class LogoComponent implements OnInit {
  @ViewChild('left') left: ElementRef
  @ViewChild('right') right: ElementRef

  ngOnInit() {
    ...doAnimationsWith(left.nativeElement, right.nativeElement)
  }
}
```

[Example with Greensock](https://teropa.info/blog/2016/12/12/graphics-in-angular-2.html#greensock)

**Comment by AltRoot17** [comment]
@MikaAK  Thanks sir
