### ISSUE TITLE
`.then` is not useable in mojs.Html tweens

### ISSUE THREAD

**Issue by kumarharsh** [mojs/mojs#190]
mojs is throwing an error while chaining the `mojs.Html` tweens with a `.then` clause.
See a reproduction here:
https://codesandbox.io/s/q8k144nrow
To see non-buggy behaviour, set the `SHOW_BUG` to `false`. 
**NOTE**: the error won't show up on first run, but on subsequent runs. So, to reproduce the bug, just change any value in the tween functions to force a re-render, or just re-set the `SHOW_BUG` to `true` after setting it to `false`.

From my investigation, I can see that while evaluating the `.then` clause, the whole `props` object is also being passed to the `createDeltas` function. This does **not** happen in other tweens (`.Shape` for example). For an object of the `Html` tween instance though, the final effect this `prop` property being passed into `createDeltas` is that mojs tries to parse a colour from the `el` property and fails, causing an exception.

I think the `el` (or the `prop`) property must be excluded from being passed into `createDeltas` somewhere near this place:

https://github.com/legomushroom/mojs/blob/51f5bf524db050fe72315df09c175a8a336e99e0/js/html.babel.js#L208-L229

@legomushroom any pointers?

**Comment by kumarharsh** [comment]
Investigating further, it seems that the actual problem is not that `props` is being passed into `createDeltas`, but that the `_makeColorObj` is not returning correct color object on all runs other than the first run.

https://github.com/legomushroom/mojs/blob/51f5bf524db050fe72315df09c175a8a336e99e0/js/delta/deltas.babel.js#L472

On non-first runs in the codesandbox, the `h.computedStyle(h.div).color` is an empty string, which is failing the subsequent regex check.

**Comment by xavierfoucrier** [comment]
Hi @kumarharsh,

I am not able to reproduce the bug because the current codesandbox doesn't work anymore.
Here is the code I am using and that works fine locally on the latest `@mojs/core` version:

```js
let tween = new mojs.Html({
  el: '.box',
  scale: {
    0: 10,
  }
}).then({
  scale: {
    10: 0,
  },
});
```

Feel free to update your code and let us know if it's still not working.
Thanks!

**Comment by kwhitejr** [comment]
Total tangent, but any idea why `.then()` blocks break in Jest? I get error such as

```
TypeError: Cannot read properties of null (reading '4')

      86 |       duration: timelineDuration,
      87 |     })
    > 88 |       .then({
         |        ^
      89 |         opacity: { 1: 0 },
      90 |         y: -80,
      91 |         delay: timelineDuration / 2,
```

But the issue disappears if the `then` block is disabled (to the detriment of the visual, obviously :D ).

**Comment by Sandstedt** [comment]
No idea 🤔, could you set a breakpoint and step through the Jest process and see where it breaks?
