### ISSUE TITLE
What is the _o object?

### ISSUE THREAD

**Issue by Meai** [mojs/mojs#194]
Hi sorry if this is a simple documentation issue but I dont get what it does or what it's supposed to be doing I guess. Isn't properties already used to inject the module with new stuff, why another _o object that is used separately? And if _o is just for additional properties then why does it continue to be used through the code instead of just being copied over to the class.

**Comment by xavierfoucrier** [comment]
Hi @Meai,

Sorry for the delay.
We are closing old issues right now.

The `_o` object is private and contains library stuff.
You don't have to rely on it to build your application.

> Note that some properties are still **historically present** and will be deleted/mangled in the future.
