### ISSUE TITLE
How to add multiple color fades for burst

### ISSUE THREAD

**Issue by dipiana** [mojs/mojs#200]
Hi,

with `{ 'green' : 'yellow' }` I can define a color-fade from green to yellow.
With `['yellow', 'green', 'orange']` I am able to define different colors for the children of a burst object.

How can I define different color-transitions for the children that the first child fades from yellow to green, the next one from blue to orange, etc.?

Cheers

**Comment by xavierfoucrier** [comment]
Hi @dipiana!

You again!! haha :smile: 
From memory, it seems to me that the library is not able to do that at this time.

Do you have a codepen to show what you are trying to do?
Thanks!

**Comment by dipiana** [comment]
Hi @xavierfoucrier , haha yes, trying to play around with mo.js a little bit 😄

I created a codepen where I want to create random gradients/color transitions for every child.
Therefore I want to be able to define colors in an array ("farben"). Each child should transist from yellow to one of these colors randomly.

Can't make it run work for every child individually, only for all children at the same time: https://codepen.io/clmsvie/pen/YJEXQO

**Comment by xavierfoucrier** [comment]
Humm.. sorry but its one of the great feature that is not implemented yet in the library.

I suggest you to use the `then()` method to **chain your animation**.
Here is a similar issue posted a year ago: https://github.com/legomushroom/mojs/issues/114.

Hope this help :wink:

**Comment by dipiana** [comment]
Oh that looks promising. I will try that asap.
Thanks a lot, @xavierfoucrier !

**Comment by dipiana** [comment]
@xavierfoucrier , I tried it but can't make it work to fade from let's say green to a given value.
It always starts fading from black.
The problem is I can't find the "to" nor "easing" in the official documentation. Am I missing something?

Thanks a lot!

**Comment by xavierfoucrier** [comment]
Hum.. well, it's because it was just **a proposal / idea** of the repository owner: it's not implemented yet, and that's why you can't make it work properly :wink:

I will try to write a code snippet tomorrow to help you find the best solution to create this fading effect.

Best regards!

**Comment by xavierfoucrier** [comment]
Hi @dipiana!

Since it's not supported by the `Burst` module at this time, here is a small **workaround** that you can try to edit and adapt to your needs:

```
let effect = new mojs.Burst({
  count: 25,
  radius: { 0 : 40 },
  children: {
    shape: 'circle',
    fill: ['#845ec2', '#d65db1', '#ff6f91', '#ff9671', '#ffc75f'],
    radius: 'rand(5, 10)',
    angle: '50',
    easing: 'linear.none',
    scale: { 1 : 0.7 },
    duration: 350,
    left: 'rand(-10, 10)',
    top: 'rand(-10, 10)'
  },
}).then({
  radius: 80,
  children: {
    fill: ['#73dbc4', '#faf7e6', '#ff008b', '#fff8a1', '#85929e'],
    easing: 'linear.none',
    scale: 0.5
  }
}).then({
  radius: 120,
  children: {
    fill: ['#1b998b', '#2d3047', '#fffd82', '#ff9b71', '#e84855'],
    easing: 'linear.none',
    scale: 0
  }
});
```

Note that I am not using the `pathScale` property because it creates a **jerk effect** between each step in this configuration, due to the random value.

Let met know if it work for you! :+1:

**Comment by dipiana** [comment]
Thank you so much @xavierfoucrier  - I really appreciate it.
Unfortunately, I can not make it work for my example as I need to use burst and it seems that therefore the dots fade to zero before `.then()` is called.

See: https://codepen.io/clmsvie/pen/YJEXQO

I wanted to create a kind of fireworks.
All the dots should burst like in the first animation, starting from one solid color, let's say red. As the animation goes on, each dot should individually fade into another color from an array - without changing the path/direction. Simply a color-change.

Do you think that is somehow possible?

Thanks so much.

**Comment by xavierfoucrier** [comment]
@dipiana UP
