### ISSUE TITLE
mojs.io not working

### ISSUE THREAD

**Issue by peterennisrda** [mojs/mojs#201]
![capture394](https://user-images.githubusercontent.com/1280523/47531414-70765d00-d862-11e8-8d0e-90067442294b.PNG)

**Comment by Tomarnst** [comment]
Yep seems to be so.... I'll think it's coming back to earlier mentions that this is not maintained anymore.

**Comment by peterennis** [comment]
@legomushroom 
If this is not maintained then it would be helpful to add a note to the repo and
possibly ask for someone to take over.

**Comment by frederick036** [comment]
You can build and serve it locally with the website repo here: https://github.com/legomushroom/mojs-website

**Comment by stupidehorizon** [comment]
That's a bad news for a new user

**Comment by Tomarnst** [comment]
@xavierfoucrier @legomushroom... any chance to start a pool of developers to get this going again ?

**Comment by xavierfoucrier** [comment]
Hi all,

I sent a message to the repository owner.

It's bad news indeed to no longer have access to the site, but as a developer, there is always a way to browse the site as indicated by @frederick036.

However for new users, see as many issues still open probably does not encourage to use this project for new developments...

As I say recently in another thread:
> ... @legomushroom may add admin contributors to help this library stay up to date.

**Comment by Sandstedt** [comment]
Ah damit, I didn't have admin rights :/ Tried to publish it on my own branch but had trouble with the super old React Router version and relative routes. So the navigation doesn't work: [https://sandstedt.github.io/mojs-website/](https://sandstedt.github.io/mojs-website/)

**Comment by xavierfoucrier** [comment]
Yes github pages is the good place to host repository website: if you have admin rights on the `mojs-website` repository, you can try to deploy the site on `gh-pages` branch. :wink:

**Comment by xavierfoucrier** [comment]
Woops... this is bad news :cry:

**Comment by afkaqualls** [comment]
I have no skills to help, but I want you all to know I am rooting for you
all to succeed so noobs like me can profit!

Alex

**Comment by xavierfoucrier** [comment]
@Sandstedt,

Do you have admin rights on mo-js?

**Comment by Sandstedt** [comment]
@xavierfoucrier nope unfortunally not.

**Comment by xavierfoucrier** [comment]
Ok, need to wait for @legomushroom. Not so easy...

**Comment by Sandstedt** [comment]
I have sent an email to Oleg and asked :) Let's see.

**Comment by xavierfoucrier** [comment]
Hi @Sandstedt,

I agree with what you say, but I would like to have the position of @legomushroom before embarking on this adventure, let's see if we got an answer shortly :wink:

**Comment by JianLoong** [comment]
Let's hope so. :+1:

**Comment by Sandstedt** [comment]
@xavierfoucrier Yes of course, it’s his baby. That’s why I sent an email. I’ll get back as soon as I hear something.

**Comment by nibushibu** [comment]
Unfortunately, he tweets that this project is no longer under maintenance.
https://twitter.com/legomushroom/status/1056990310218133504

**Comment by xavierfoucrier** [comment]
Ok, we finally have our answer :+1: 

I have my own organization @studiomotio, so I can put a fork of `mojs` in, create a specific **team** and add **collaborators** with push access. Let me know if it's a good thing or if you want to create a specific organization for that, like webpack we could use `mojs-contrib` :yum:

**Comment by peterennis** [comment]
@xavierfoucrier 
I am interested in the future of this. Looking at the history it seems the lack of desire
to support mojs is that the technology is old and legomushroom is now part of Microsoft. I guess
they have a different vision.
I have not looked at v2 but would like to see the project move towards components that can
be easily integrated with Angular, React, Vue, etc.
I have been following Stencil.js (https://stenciljs.com/) and it promises to be a good cross-framework component compiler.

**Comment by xavierfoucrier** [comment]
Yep, I agree with a **dedicated organization**.

I work with `mojs` since 2 years now, and I am not sure that the project will move towards reusable components for Angular, React and Vue... though I have seen many developers working to implement `mojs` with web frameworks. May be I am wrong, but `mojs` is made for tailor made and custom web animations.

Let's see all **feedbacks** from other members/contributors :wink:

**Comment by Tomarnst** [comment]
So any concrete plans ? Maybe organize a bit to make this move forward ?

**Comment by xavierfoucrier** [comment]
As I previously said, we are waiting for **feedback from other members/contributors**, especially people that already pushed code fix/feature or pull requests on this repo. Keep calm, and be patient :wink:

**Comment by xavierfoucrier** [comment]
20 days later: I am currently working on a new projet with the Popmotion library... not as easy as mojs... but provide useful features. For curious peoples: https://popmotion.io

Next year, if nothing has moved here, I will create the organization+repo as described in  https://github.com/legomushroom/mojs/issues/201#issuecomment-438598178 to make the mojs project keep moving forward.

Don't hesitate to show your interest and let all know if you want to contribute!
See you :wink:

**Comment by frederick036** [comment]
I think we need to get the website back up running again first.

**Comment by rordi** [comment]
the url points to some spam ads network. please at least remove the spam link from the github repo.

**Comment by peterennisrda** [comment]
@xavierfoucrier, @rordi 
Reported abuse to GitHub/Microsoft
Maybe we will get some attention to this.
![capture482](https://user-images.githubusercontent.com/1280523/50022380-caf18700-ff90-11e8-99a7-31103df98e0a.PNG)
![capture483](https://user-images.githubusercontent.com/1280523/50022384-ce850e00-ff90-11e8-8fff-c0f741c3b68d.PNG)
![capture484](https://user-images.githubusercontent.com/1280523/50022389-d2189500-ff90-11e8-9c06-b0217987bcd2.PNG)

**Comment by xavierfoucrier** [comment]
@peterennisrda yes hope that help to fix the problem. It seem's that @legomushroom has not renew the domain name... :'(

**Comment by frederick036** [comment]
@peterennisrda I don't think it's hijacked by spammers. @legomushroom didn't renew the domain and someone else bought it. I don't think we should expect @legomushroom to do anything more either as he already said it's a deprecated project. If we want to continue development, we need to host it somewhere else on some other domain, and update the read me file to let people know.

**Comment by shengslogar** [comment]
This repo should be archived or at least a note should be added indicating its deprecated status in the README. The now spammy mojs.io is the second result on Google and that's not a good thing. Ping @legomushroom

**Comment by peterennisrda** [comment]
@frederick036 
The site is used for spam under false pretenses of being mojs.

@shengslogar, @xavierfoucrier 
I got a response from github:

```
On Fri, Dec 14, 2018 at 6:40 PM GitHub Staff <support@github.com> wrote:
Hi Peter,

Thanks for taking the time to let us know. We're investigating the user.

Thanks,
GitHub Staff
```

**Comment by frederick036** [comment]
@peterennisrda There's nothing to fix or investigate. Unless you wanna pay for the domain yourself, there's not much we can do apart from updating the read me file and move away from mojs.io. Your having them investigating @legomushroom is unnecessary too as he already said this repo is deprecated. Moving on, we'll need to use some other domain to host the site.

**Comment by peterennisrda** [comment]
@frederick036 @legomushroom 
This: https://github.com/legomushroom/mojs/issues/201#issuecomment-433475695
I understand the repo is deprecated. Announcing it on twitter https://github.com/legomushroom/mojs/issues/201#issuecomment-438574253 does not solve the main issue.
The owner is not responsive and it does no credit to his years of work to leave a legacy of spam.
If the solution is to pay for the domain I would do that and then pass it over to a future maintainer
or project. However, the mojs site has been "hijacked" (i.e. purchased for the benefit of fake news :)
As I understand, there is nobody with admin rights to even fix the link and make a deprecated announcement in the readme.
This: https://github.com/legomushroom/mojs/issues/201#issuecomment-447932266
Ping: https://github.com/legomushroom/mojs/issues/201#issuecomment-433475695 https://github.com/legomushroom/mojs/issues/201#issuecomment-435313465 https://github.com/legomushroom/mojs/issues/201#issuecomment-435318470 
and this comment.

**Comment by DanielRuf** [comment]
Is there any news about the planned org?

**Comment by xavierfoucrier** [comment]
Hi everyone, happy new year to all of you :tada: 

As expected, I have created the @mojs-contrib organization yesterday and fork the main repositories of the mojs project:
- mojs
- mojs-player
- mojs-curve-editor
- mojs-timeline-editor

If you are interested to **become a contributor**, propose new features, fix bugs or simply write API documentation, drop me your Github account to **join the team and get push access**. Star the repo to show your interest.

Feel free to tell me if you have any suggestions regarding the organization/team/repo.

See you soon! :sunglasses:

**Comment by xavierfoucrier** [comment]
For thoose who want to join the **@mojs-contrib** team and continue to contribute to mojs, join the `#mojs-contrib` Slack channel here: https://mojs.slack.com/messages/CFT8GCJBG.

Drop your Github account to get push access! :heart:

**Comment by frederick036** [comment]
@xavierfoucrier you have to get invited to the Slack channel right? Here's my email: frederick036@gmail.com. Thanks!

**Comment by xavierfoucrier** [comment]
Hi @frederick036!
Welcome in the team, I will add you soon.

Yes, I have created a channel inside the "old" mojs workspace, managed by legomushroom, other peoples can't join easily in fact... I will take time to create a specific workspace for this org shortly and will share the invite link :+1:

**Comment by xavierfoucrier** [comment]
For thoose who want to join the **@mojs-contrib** team and continue to contribute to mojs, join the new `mojs-contrib` Slack workspace: https://join.slack.com/t/mojs-contrib/shared_invite/enQtNTQwNDg2NTgyNDg3LWExZjQ1MGMzOThjYzg1Njk5MThlYzcxZTMyM2NlYmJmNGYxM2U3ZTAyMDUzMWVlZWU2ZjBkYmFkMDU3ZmNkNjE

Drop your Github account to get push access! :heart:

**Comment by xavierfoucrier** [comment]
@DanielRuf would you like to join the mojs-contrib team on Github? I am currently "merging" all pull requests from https://github.com/legomushroom/mojs/pull into the new mojs repository, but the pull request [you made](https://github.com/legomushroom/mojs/pull/186) for updating dependencies/ci is a little outdated and there are many dependencies that are not maintained anymore: need help on that.

:sunglasses:

**Comment by xavierfoucrier** [comment]
Perfect, I will add you shortly! :wink:

**Comment by joniler** [comment]
I feel like the project should just be forked and active maintainers should be re-added to the fork... Then at least people looking for this won't accidentally be served up malicious spam sites when trying to look at the project website.

**Comment by DanielRuf** [comment]
> I feel like the project should just be forked and active maintainers should be re-added to the fork... Then at least people looking for this won't accidentally be served up malicious spam sites when trying to look at the project website.

It is already forked or what do I oversee? There are currently no active maintainers here.

**Comment by Sandstedt** [comment]
@joniler I know you have helped out before. The problem is that no one except @legomushrom himself has write access to the repos. So we can't do anything more here without his help. We have reach out to both GitHub and Microsoft to help out but no answers yet. 

So in the meantime we have started mojs-contrib that is a direct fork of mojs and all its sub repos including the website and tools. You're more then welcome to join the work there 🙂.

**Comment by WagnerMoreira** [comment]
if we try http://mojs.io/ right now it's going to scam/crazy adds pages

**Comment by DanielRuf** [comment]
> if we try http://mojs.io/ right now it's going to scam/crazy adds pages

We already know that and have no control over it. Someone else owns the domain.

**Comment by xavierfoucrier** [comment]
@joniler: want to join? :smiley:

**Comment by joniler** [comment]
Yeah, sign me up. I'm down to help out with various things in relation to
keeping the project alive. I may or may not contribute to the code base,
just because it's a bit over my head in terms of skell level at the moment
haha.

**Comment by xavierfoucrier** [comment]
Hi everyone!

I recently got an invite from @legomushroom to join the official mojs team.

After a moment of reflection, I accepted this invitation in order to help in the project's evolution and to prevent the repository from being abandoned, since there is much more followers and contributors on it as our unofficial fork.

As we have not touched the core source code of the library, it is not too late to backtrack and return to the official mojs repository.

In an immediate future, I keep the @mojs-contrib organization open as well as the workspace on Slack.

For those who want to support and contribute to @mojs, come back to the official repository. The roadmap would probably be similar to the unofficial fork.

As for @mojs-contrib, I would do my best to contribute to the library since I have new projects this month with my studio and other open source projects.

Thanks for all your support!
Let's make mojs sparkle again! :tada:

**Comment by peterennis** [comment]
@xavierfoucrier  - Glad to hear the news 😃  Does that mean @legomushroom will provide some help and/or guidance? As mentioned on slack I am only interested in v2+ development and have no attachment to the legacy code.

**Comment by xavierfoucrier** [comment]
@legomushroom will continue to help on this project when he will have more time, but as mentioned, **the roadmap would probably be similar to the unofficial fork**, so for now, the v2 will remain in a pending status.

I lock this conversation to prevent future off topics comments.
