### ISSUE TITLE
Not sure this regex does what you intend

### ISSUE THREAD

**Issue by LouisMichael** [mojs/mojs#206]
On[ line 7429 of mo.js](https://github.com/legomushroom/mojs/blob/51f5bf524db050fe72315df09c175a8a336e99e0/build/mo.js#L7429) you use the following regex
`nRgx = /(-|\+)?((\d+(\.(\d|\e(-|\+)?)+)?)|(\.?(\d|\e|(\-|\+))+))/gim;`
where it seems like you are trying to use \e for an escape character but in javascript \e matches e literally unlike in other regex dialects

**Comment by davisjam** [comment]
That regex looks like it is capturing scientific notation, so I think "e" was intended. I am not sure why those e's are escaped though.
