### ISSUE TITLE
Error "Cannot read property '1' of null when running in Mocha/Jest test environment

### ISSUE THREAD

**Issue by stevenbirr** [mojs/mojs#207]
I am facing an issue when running mo.js in my mocha/enzyme test environment.
I have a simple component with mo.js included:

```
import mojs from 'mo-js';
...
```
When running my mocha tests, the following error occurs:
C:\my-project\node_modules\mocha\node_modules\yargs\yargs.js:1148
      else throw err
           ^
TypeError: Cannot read property '1' of null
    at Helpers.getPrefix (C:\my-project\\node_modules\mo-js\build\mo.js:1755:69)

I think, it is not possible to get the computed style from window, when running in Node test environment, right?
```
dom = "WebKit|Moz|MS|O".match(new RegExp("(" + pre + ")", "i"))[1];
```
[mo-js\build\mo.js:1755:69](https://github.com/mojs/mojs/blob/e3595f2706aab3bc07db5926568104724f0411c5/build/mo.js#L1755)

Is there any solution for that?
Kind regards,
Steven

**Comment by Sandstedt** [comment]
Maybe you can mock the window object?

**Comment by Sandstedt** [comment]
@stevenpietzsch Did you solve this? Then please close this issue, and if you have time, add a small writeup how you solved it. Thanks!

**Comment by stevenpietzsch** [comment]
No, sorry. Did not solve this problem.

**Comment by Sandstedt** [comment]
The problem doesn't have anything with window.getComputedStyle. There's some problem with the dom regex. Doesn't really understand what it does to be honest. Will need some more digging, but should definitely fix it.

**Comment by JakeHartnell** [comment]
Came across this today. Perhaps related? https://stackoverflow.com/questions/40554652/uncaught-typeerror-cannot-read-property-1-of-null-in-a-javascript-function

**Comment by xavierfoucrier** [comment]
Hi @JakeHartnell,

Thanks for your feedback. We are currently working on releasing a new version of the library, with up to date dependencies, may be this will solve the problem, will see.

If not, your comment will probably be helpful!
Have a nice day :wink:

**Comment by JakeHartnell** [comment]
I was able to get around this error by changing how imported the library. Instead of:
```
import mojs from 'mo-js';
```

I updated the React component I was working on, to import it as part of `componentDidMount`:
```
    componentDidMount() {
        const mojs = require('@mojs/core');
        ...
    }
```

This is a bit of a hack, but my tests pass now.

@xavierfoucrier, looking forward to the new version! Thank you for the work.

**Comment by xavierfoucrier** [comment]
I found the bug, working on a fix :+1:
