### ISSUE TITLE
Fix dependencies

### ISSUE THREAD

**Issue by DanielRuf** [mojs/mojs#211]
After changing `"git+https://github.com/legomushroom/grock.git"` to `legomushroom/grock` we still have some issues with other dependencies:

```
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/Nikku/node-browserify.git
Directory: /Users/druf/projects/mojs
Output:
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

```
6878 silly resolveWithNewModule watchify@2.2.1 checking installable status
6879 silly fetchPackageMetaData error for browserify@github:Nikku/node-browserify#local-fix Error while executing:
```

```
6882 silly saveTree ├─┬ karma-browserify@2.0.0
6882 silly saveTree │ ├── convert-source-map@0.3.5
6882 silly saveTree │ ├── js-string-escape@1.0.1
6882 silly saveTree │ ├── lodash@2.4.2
6882 silly saveTree │ ├── minimatch@1.0.0
6882 silly saveTree │ └── watchify@2.2.1
```

So it seems `karma-browserify > watchify` is the culprit.

**Comment by xavierfoucrier** [comment]
Hi @DanielRuf,

Yes, of course all dependencies need to be updated on this project, many are deprecated but we are still working on the website with @Sandstedt. If you want to PR something, it is more than welcome :wink:

**Comment by DanielRuf** [comment]
> Seems that you already have a PR in the pipe: #186

Right but I have to check against the current state again as we have no lockfile.
https://travis-ci.org/mojs/mojs/builds/368854050

We should probably pin the dependencies in package.json then as lockfiles are not used on npmjs and when adding / installing dependencies - just the root lockfile actually locks.

**Comment by xavierfoucrier** [comment]
I agree with you, we need to have a **package-lock.json** file in order to properly have dependencies pinned.

I am very busy since 1 month, but if you are able to make a new PR or update the existing one, don't hesitate to ping me on the Slack channel :wink:
