### ISSUE TITLE
In Bubble layout example tween.add is giving error with latest version(  "@mojs/core": "^0.288.2")

### ISSUE THREAD

**Issue by SuneethaYamani** [mojs/mojs#218]
As per latest version api only timeline has add method.
So in bubble layout example i changed code like this

   this.showCloseBtnTween = new mojs.Timeline();
      this.showCloseBtnTween.add(
        this.closeCircle.tween,
        this.closeCircle2.tween,
        this.closeCircle3.tween,
        this.closeCircle4.tween,
        this.closeCross.tween,
        this.closeBurst.tween
      );
      this.showCloseBtnTween.play();

I am getting below error "ERROR TypeError: Cannot read property 'timeline' of undefined"

**Comment by xavierfoucrier** [comment]
Hi @SuneethaYamani,

Sorry to hear that, but the bubble layout example **is running under v0.119.0** on CodePen and can't probably run with the latest version.

**Comment by Sandstedt** [comment]
There is some working examples here if you wanna read more how to make the burst effects: https://mojs.github.io/tutorials/burst

**Comment by JEricFarias** [comment]
Hi @SuneethaYamani 
You can run `npm i mo-js@0.119.0` to get the specific version. I found this in the release tree [here](https://github.com/mojs/mojs/tree/0.119.0)
