### ISSUE TITLE
How to use mojs with angular,Help needed

### ISSUE THREAD

**Issue by SuneethaYamani** [mojs/mojs#219]
Please give some documentation for mojs with angular

**Comment by xavierfoucrier** [comment]
Hi @SuneethaYamani,

For now, **we haven't planned to add official support for Angular**.
Please take a look at the previous issues that could probably help you a little if you have some problems with the API and Angular: https://github.com/mojs/mojs/issues?utf8=%E2%9C%93&q=is%3Aissue+angular.

Thanks :wink:
