### ISSUE TITLE
How to build an infinite repeat animation?

### ISSUE THREAD

**Issue by GaoHengdong** [mojs/mojs#223]
I found isYoyo not working when repeated  using function onComplete. 
```
new mojs.Shape({
  parent:       '#loader',
  shape:        'circle',
  fill:         'none',
	stroke:       '#4792e6',
	strokeWidth:  5,
  strokeLinecap:'round',
	strokeDasharray:{'110 15':'80 45'},
  radius:       20,
  duration:     2000,
  isYoyo:       true,
  isShowStart:  true,
	onComplete:function(){this.replay()}
}).play();
```
this is my code. Could anyone help me? Is this a bug? 
Thank you.

**Comment by xavierfoucrier** [comment]
Hi @GaoHengdong,

This is probably not the right syntax...
Calling the `replay` method will just **restart the animation from zero**.

`isYoyo` is aimed to work with the `repeat` option, that is set to `0` by default.. so you just need to set it with the number of time you want your animation to be repeated, like this:

```js
new mojs.Shape({
  ...
  repeat: 20,
  isYoyo: true,
  onComplete: function() {
    this.replay();
  })
});
```

Hope this help :wink:

**Comment by GaoHengdong** [comment]
Hi @xavierfoucrier ,
Thank you for your reply.
Actually I just want to find a 'repeat : infinete‘ alternative. Issue #78 has discussed about it. But actually,
```
  onComplete: function() {
    this.replay();
  })
```
can't be a  equally solution to 'repeat : infinete‘ .
Your code above will cause a break when repeated 20 times.
My idea is manually implement isYoyo by then() or repeat really large times.
Is there a better way? Thank you!😄

**Comment by xavierfoucrier** [comment]
Hi @GaoHengdong,

Of course you can!
Here is the trick: use `repeat: 1` and `this.replay()` at the same time.

```js
new mojs.Shape({
  parent: '#loader',
  shape: 'circle',
  fill: 'none',
  stroke: '#4792e6',
  strokeWidth:  5,
  strokeLinecap:'round',
  strokeDasharray:{'110 15':'80 45'},
  radius: 20,
  duration: 2000,
  isYoyo: true,
  repeat: 1,
  isShowStart: true,
  onComplete: function() {
    this.replay();
  }
}).play();
```

This will play the first stage, then at 50% progress will flip your animation (due to the `isYoyo` option), and finally, when reaching 100% of the progress, will replay the shape, causing an infinite repeat chain.

You can close the issue if it fits your needs.

:tada: :wink:

**Comment by GaoHengdong** [comment]
OK. Thank you!
