### ISSUE TITLE
Lack of .babelrc file is causing an error on watch

### ISSUE THREAD

**Issue by Sandstedt** [mojs/mojs#225]
When building the mojs project (`npm run start`), and have an .babelrc file in a parent folder, babel will try to find a .babelrc file in any of it's parent folders, and if it will, it will use that instead. This could cause a corrupt build or resulting in an error like this:

```
ERROR in ./js/mojs.babel.js
Module build failed: ReferenceError: Unknown plugin "styled-components" specified in "/Users/Sandstedt/pages/.babelrc"
```

To temporally solve this, make sure you don't have any .babelrc files laying around in your parent folders.

Will probably be solved to either add an empty .babelrc file, move current babel settings to a .babelrc file or add some settings to our webpack babel settings saying it should not try looking for this settings file.

**Comment by xavierfoucrier** [comment]
We will probably move the babel configuration into a dedicated `.babelrc` file :wink:
