### ISSUE TITLE
Repeat Burst before it finished

### ISSUE THREAD

**Issue by dipiana** [mojs/mojs#232]
Hello,

is there a way to repeat a burst animation (which takes 3 seconds) every second that a kind of ripple effect is created.

Thanks a lot!

**Comment by xavierfoucrier** [comment]
Hi @dipiana!

You can use the `repeat` option of the `Burst` children to repeat it, like this:

```js
new mojs.Burst({
  radius: { 0 : 100 },
  count: 10,
  children: {
    shape: 'circle',
    fill: 'blue',
    duration: 3000,
    repeat: 100
  }
}).play();
```

As the `Burst` doesn't have an "infinite" value for the `repeat` option, you can use the `onComplete` hook to repeat it by yourself, like this:

```js
const round = new mojs.Burst({
  radius: { 1 : 100 },
  count: 20,
  children: {
    shape: 'circle',
    fill: 'blue',
    duration: 3000
  },
  onComplete: function() {
    this.replay();
  }
}).play();
```

This two examples will produce the same result:
![Sans-titre---1](https://user-images.githubusercontent.com/2471223/75666510-35feaa80-5c76-11ea-967c-779d094edcae.gif)

Hope this help!

> Note that you can produce a "ripple" effect by just using a circle `Shape` :wink:

**Comment by Sandstedt** [comment]
@dipiana You can also use the [timeline function](https://mojs.github.io/api/tweens/timeline.html) and pass in multiple burst animations, like in this example: https://codepen.io/sandstedt/pen/ExjvLrr?editors=0010, if that is more the effect you want.

Else if you have a Dribbble animation or something as a reference we could help you recreating it 🙂

**Comment by dipiana** [comment]
Hey! Thanks for your help.

I am actually looking for a different effect.
Let's say one burst animation takes 2 seconds (from where the points are created until they traveled away from the center and dissolve). Now I would like to have a new burst created every 0.5 seconds, so before the first burst even finished.

My desired end result should look like this one here: 
![compressionwave](https://user-images.githubusercontent.com/7633078/76141788-d9313480-6067-11ea-8738-15e9b9a0adec.gif)

Would appreciate your help a lot!

Thanks :)

**Comment by xavierfoucrier** [comment]
Hi @dipiana,

Thanks for the gif. sounds a little complex to build, but have started something and will share when the result will be as close as possible to yours :wink:

**Comment by xavierfoucrier** [comment]
Hi @dipiana,

Here is a good starting point: adapt it to your needs of course :wink: 

Your animation is made, for me, of two things:

1. A **ripple** effect: points placed on circles that grow up from the center, and finally disappear when reaching the maximum radius. My solution is to **only use 5 `Burst` of 30 points that will repeat infinitely**, this way you won't have a lot of browser memory consumption.
```js
for (let r = 0; r < 5; r++) {
  new mojs.Burst({
    radius: { 20 : 300 },
    count: 30,
    angle: 'rand(0, 360)',
    isForce3d: true,
    children: {
      shape: 'circle',
      fill: 'black',
      scale: 1,
      opacity: { 1 : 0, easing: mojs.easing.quint.in },
      radius: 'rand(2, 3)',
      duration: 5000,
      delay: 1000 * r + 120
    },
    onComplete: function() {
      this.tune({
        children: {
          delay: 120
        }
      }).generate().replay();
    }
  }).play();
}
```
> Note that the ripple effect is triggered **every second** on this example, but you can reduce this time to fit your needs: be sure to adjust the `120ms` delay to keep the "synchronization" between the ripple and the pulse effect.

2. A **pulse** effect: points placed randomly in space, like molecules, that need to bounce accordingly to the ripple effect. The solution is to create multiple `Burst` with random count/angle/radius/opacity.
```js
for (let p = 1; p <= 30; p++) {
  new mojs.Burst({
    count: 'rand(3, 10)',
    angle: 'rand(0, 360)',
    radius: { [`rand(${8 * p}, ${10 * p})`] : `rand(${10 * p}, ${12 * p})` },
    isShowStart: true,
    isForce3d: true,
    children: {
      shape: 'circle',
      fill: 'black',
      opacity: 'rand(0, 1)',
      scale: 1,
      radius: 2,
      duration: 500,
      isShowStart: true
    },
    timeline: {
      repeat: 1,
      isYoyo: true,
      onComplete: function() {
        this.replay();
      }
    }
  }).play();
}
```
> Be aware that running too many `Burst` at the same time can add browser lag issues.

Finally, here is the browser rendering _(size smaller that the real output)_:
![Sans-titre---3](https://user-images.githubusercontent.com/2471223/76204966-a7e86e00-61f9-11ea-9445-660a2185b2e7.gif)

Enjoy the power of **mojs** :sunglasses: :tada:

Hope this help!
Feel free to close the issue when it's good for you :+1:

**Comment by dipiana** [comment]
Really cool! Thanks for the input! :)
