### ISSUE TITLE
How to add custom shapes by es5?

### ISSUE THREAD

**Issue by pzxie** [mojs/mojs#235]
Is there a way to add custom shapes with es5? 
I tried to use prototype to inherit mojs.CustomShape, but it didn't  work. Anyways to solve it? Thanks!

**code show as below** 
```` javascript
function Heart () {
  mojs.CustomShape.call(this)
}
Heart.prototype = Object.create(mojs.CustomShape.prototype)
Heart.prototype.constructor = Heart
Heart.prototype.getShape = function () {
  return '<path d="M92.6 7.4c-10-9.9-26-9.9-35.9 0l-4.4 4.3a3.4 3.4 0 0 1-4.7 0l-4.3-4.3c-10-9.9-26-9.9-35.9 0a25 25 0 0 0 0 35.5l22.4 22.2 13.5 13.4a9.5 9.5 0 0 0 13.4 0L70.2 65 92.6 43a25 25 0 0 0 0-35.5z"/>'
}
Heart.prototype.getLength = function () {
  return 200
}

mojs.addShape('heart', Heart)

const heart = new mojs.Shape({
  shape:    'heart', // <--- shape of heart is now available!
  fill:     'none',
  stroke:   'red',
  scale:    { 0 : 1 },
  strokeWidth: { 50 : 0 },
  y:         -20,
  duration:  1000,
});
````

**ES6 class is works**
```` javascript
class Heart extends mojs.CustomShape {
  getShape () { return '<path d="M92.6 7.4c-10-9.9-26-9.9-35.9 0l-4.4 4.3a3.4 3.4 0 0 1-4.7 0l-4.3-4.3c-10-9.9-26-9.9-35.9 0a25 25 0 0 0 0 35.5l22.4 22.2 13.5 13.4a9.5 9.5 0 0 0 13.4 0L70.2 65 92.6 43a25 25 0 0 0 0-35.5z"/>'; }
  getLength () { return 200; } // optional
}
````

**Comment by Sandstedt** [comment]
Me personally always use Babel for everything nowadays. But sure there is a way to compile it manually. Don't have the syntax in my head currently, but can make an example later. But if you need to support IE11 and below, I would encourage you to use a compile step anyway.

**Comment by Sandstedt** [comment]
Okay, got it working 😀

Here is an complete example: https://codepen.io/sandstedt/pen/JjdZyXg?editors=0010

```
function Heart() {
  return Reflect.construct(mojs.CustomShape, arguments, Heart)
}
Reflect.setPrototypeOf(Heart.prototype, mojs.CustomShape.prototype)
Reflect.setPrototypeOf(Heart, mojs.CustomShape)

Heart.prototype.getShape = function () { return '<path d="M92.5939814,7.35914503 C82.6692916,-2.45304834 66.6322927,-2.45304834 56.7076029,7.35914503 L52.3452392,11.6965095 C51.0327802,12.9714696 48.9328458,12.9839693 47.6203869,11.6715103 L47.6203869,11.6715103 L43.2705228,7.35914503 C33.3833318,-2.45304834 17.3213337,-2.45304834 7.43414268,7.35914503 C-2.47804756,17.1963376 -2.47804756,33.12084 7.43414268,42.9205337 L29.7959439,65.11984 C29.7959439,65.1323396 29.8084435,65.1323396 29.8084435,65.1448392 L43.2580232,78.4819224 C46.9704072,82.1818068 52.9952189,82.1818068 56.7076029,78.4819224 L70.1696822,65.1448392 C70.1696822,65.1448392 70.1696822,65.1323396 70.1821818,65.1323396 L92.5939814,42.9205337 C102.468673,33.12084 102.468673,17.1963376 92.5939814,7.35914503 L92.5939814,7.35914503 Z"></path>'; }
Heart.prototype.getLength = function () { return 200; } // optional

mojs.addShape('heart', Heart);

var heart = new mojs.Shape({
  shape: 'heart',
  fill: 'none',
  stroke: 'purple',
  scale: {
    0: 1
  },
  strokeWidth: {
    50: 0
  },
  y: 100,
  duration: 1000,
  repeat: 100,
}).play();
```

**Comment by Sandstedt** [comment]
Oh sorry. I see Reflect isn't working in IE.

**Comment by xavierfoucrier** [comment]
Hi @pzxie!

I agree with @Sandstedt, you should use **Babel** to transpile your code, this is the better way in 2020.

Or, if you don't want to use Babel, you can polyfill the `Reflect` class, simply as that by using the **Polyfill.io** URL service: https://polyfill.io/v3/polyfill.min.js?features=Reflect.setPrototypeOf%2CReflect.construct

> See https://polyfill.io/v3/ for more informations

:wink:

**Comment by pzxie** [comment]
> Hi @pzxie!
> 
> I agree with @Sandstedt, you should use **Babel** to transpile your code, this is the better way in 2020.
> 
> Or, if you don't want to use Babel, you can polyfill the `Reflect` class, simply as that by using the **Polyfill.io** URL service: https://polyfill.io/v3/polyfill.min.js?features=Reflect.setPrototypeOf%2CReflect.construct
> 
> > See https://polyfill.io/v3/ for more informations
> 
> 😉

@xavierfoucrier  Yes, agree with u, actually i did it.  But i just want to try the way by es5, After all, class is just syntactic for functions.  :smile:

**Comment by xavierfoucrier** [comment]
Perfect, try to use a Polyfill and feel free to close the issue when it is good for you. :sunglasses:
