### ISSUE TITLE
Z index in documentation site

### ISSUE THREAD

**Issue by nainardev** [mojs/mojs#236]
![Screenshot_20200410-130936](https://user-images.githubusercontent.com/59839368/78972990-9a8e0e80-7b2c-11ea-8803-a6bb7dbe87e2.png)
![Screenshot_20200410-130928](https://user-images.githubusercontent.com/59839368/78973003-9eba2c00-7b2c-11ea-9df3-324877ac8d4f.png)

**Comment by Sandstedt** [comment]
Thanks @nainardev! It's fixed now.

**Comment by nainardev** [comment]
How did you implemented it? Can you reference the commit?

**Comment by Sandstedt** [comment]
@nainardev Sure. Here's the commit: [https://github.com/mojs/mojs.github.io/commit/559d1a1bada81687602d785dd1aaea2cc15cabe7](https://github.com/mojs/mojs.github.io/commit/559d1a1bada81687602d785dd1aaea2cc15cabe7)
