### ISSUE TITLE
What is the difference between play and replay?

### ISSUE THREAD

**Issue by Viksna-Maxim** [mojs/mojs#237]
When I use the `replay()` to run an animation, the animation doesn't work correctly (there are several multiple iterations of the animation that shouldn't be there). However, when I use the `play()` to run animation, it all works well, without any repetitions. 
**Question:** 
1. Why is this happening?
2. What is the difference between the `play()` and `replay()` in my case ([codepen](https://codepen.io/maxviksna/pen/xxwbGrM) (pay attention to event listener))?

**Comment by Sandstedt** [comment]
What's happens here is that you for each click adds some animation data to the timeline using `.then()` on each polygon. You don't redefine the animation, you add to the chain. Like an array push.

So when you use `.play()`, you starts playing from the timeline position where you stopped last time, and plays through the newly added animation data that you declared in the `.then()` function.

When you instead use `.replay()`, you restart the entire animation from frame 0. So each time you click now, you will add some more animation data and play from the beginning.

So the difference is that with `.play()` you start playing the animation/timeline from where you last stopped (with an optional parameter to shift the animation from that time on space), and with `.replay()` you start from the beginning of the animation/timeline.

**Comment by Viksna-Maxim** [comment]
@Sandstedt, thank you!

**Comment by Viksna-Maxim** [comment]
@Sandstedt, how can I redefine the animation? What's the method I need?

**Comment by Viksna-Maxim** [comment]
@Sandstedt, I have a lot of questions should I create a new issues every time?

**Comment by xavierfoucrier** [comment]
@Viksna-Maxim, of course not :smile: !

If you doesn't find any answer on Github issues+mojs docs, please **join the Slack channel** in order to ask your questions: https://join.slack.com/t/mojs/shared_invite/zt-dcqt2syv-2ndsIdesrutP28AyAqZSfg.

Thanks a lot!

**Comment by Viksna-Maxim** [comment]
@Sandstedt, can you help? Please explain to me why this code doesn't work
```
const btn = document.querySelector('#btn');
const myCurve = "M0, 100 C0, 100 44.87788059660561, -39.91911058306421 55, -50 C65.12211940339441, -60.08088941693578 60.41952358273102, 29.403014378078353 70, 40 C79.58047641726898, 50.59698562192165 92.68868024988831, -14.728263011137487 95, -15 C97.31131975011169, -15.271736988862513 100, 0 100, 0 ";
const myCurve2 = "M0, 100 C0, 100 6.761905065604619, 110 6.761905065604619, 110 C6.761905065604619, 110 15, 70 15, 70 C15, 70 30, 140 30, 140 C30, 140 100, 0 100, 0 ";

const OPTS = {
    parent:         btn,
    shape:          'rect',
    fill:           'red',
    rx:             '2px',
    ry:             '2px',
    radiusX:         2,
    isShowStart:      true,
    isShowEnd:        true,
    duration:       200
};

const polygon1 = new mojs.Shape({
    ...OPTS,
    radiusY:         10,
    angle:          90,
    left:           30,
    top:            30,
    x:              {0:3},
    y:              {0:3},
});

const polygon2 = new mojs.Shape({
    ...OPTS,
    radiusY:         20,
    angle:          90,
    left:           40,
    top:            40,
});

const polygon3 = new mojs.Shape({
    ...OPTS,
    radiusY:         10,
    angle:          90,
    left:           50,
    top:            50,
    x:              {0:-3},
    y:              {0:-3},
});

const timeline = new mojs.Timeline();

timeline
.add(
    polygon1, polygon2, polygon3
);

new MojsPlayer({ add: timeline, isPlaying: true });

var isOpen = false;

btn.addEventListener( 'click', function () {

    if(!isOpen) {

        polygon1
        .tune({ angle: {90:135, easing: myCurve} })
        .replay();

        polygon2
        .tune({ angle: {90:45, easing: myCurve} })
        .replay();

        polygon3
        .tune({ angle: {90:135, easing: myCurve} })
        .replay();

        isOpen = !isOpen;
    } else {

        polygon1
        .tune({ angle: {90:135, easing: myCurve2} })
        .replayBackward();

        polygon2
        .tune({ angle: {90:45, easing: myCurve2} })
        .replayBackward();

        polygon3
        .tune({ angle: {90:135, easing: myCurve2} })
        .replayBackward();

        isOpen = !isOpen;
    }
});
```

**Comment by xavierfoucrier** [comment]
@Viksna-Maxim please ask on Slack as I said... thanks.
