### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by jawahar95** [mojs/mojs#243]
Give support to SSR.
Am using this package in angular server side rendering It show error while  generating a SSR build

**Comment by AsifDeveloper** [comment]
Yes, I am also getting the same issue while using this package in the Angular SSR build.

**Comment by xavierfoucrier** [comment]
Hi @jawahar95,

Can you give us a little more informations about the error you are encountering when building with an SSR application and at least, a minimal reproductible test repository?

Thanks :wink:

**Comment by Sandstedt** [comment]
Usually it has to do that mojs try to access the window object that doesn't exist on a node server. 

So best is to not try to run a client side library on the server. Angular should have documentation how to do this. 

But we could probably do a quick test and see if it's run on the server, and just abort.

**Comment by xavierfoucrier** [comment]
@Sandstedt you are right, I think checking the environment/window object should do the trick.
Waiting for @jawahar95 feedback if there is other issues/errors that he want talk about :wink:

**Comment by jawahar95** [comment]
here I share the deceleration of mojs  if am declear the mojs DOM element Wont render 
![Screenshot from 2020-09-07 16-30-29](https://user-images.githubusercontent.com/36267622/92380879-7d835900-f127-11ea-8db5-f342918e145a.png)
  
tlDuration = 300;
  @ViewChild('anibutton', {static: true}) clap: ElementRef;
  triangleBurst = new mojs.Burst({
    parent: this.clap,
    radius: {50: 95},
    count: 5,
    angle: 30,
    children: {
      shape: 'polygon',
      radius: {6: 0},
      scale: 1,
      stroke: 'rgba(211,84,0 ,0.5)',
      strokeWidth: 2,
      angle: 210,
      delay: 30,
      speed: 0.2,
      easing: mojs.easing.bezier(0.1, 1, 0.3 , 1),
      duration: this.tlDuration
    }
  });

**Comment by xavierfoucrier** [comment]
Hi @jawahar95,

OK so this is exactly was @Sandstedt underlined!
This will be fix in the next release :wink:

**Comment by jawahar95** [comment]
when we can expect the next release

**Comment by xavierfoucrier** [comment]
@jawahar95 next release is planned in the Github milestone, approx. October 31, 2020... but it will depend on some feedback that we are waiting about the CI/CD pipeline.

**Comment by xavierfoucrier** [comment]
After a lot of tests/hours trying to make the (current) library compatible with SSR, we have decided with Jonas to not make the current mojs version SSR-friendly. Documentation will state about this inside the React section and you will be able to find an example on how to properly implement this kind of library inside an SSR application.
