### ISSUE TITLE
Export the DOM animation to a single SVG file

### ISSUE THREAD

**Issue by ebookpk** [mojs/mojs#244]
How can I export the dom animation to a single svg file

**Comment by Sandstedt** [comment]
Interesting question. I guess you could paus the animation at the time you wanna save as an SVG (example using mojs timeline), and then inspect the DOM in your browsers dev tools and copy the sourunding SVG DOM and save to a file.

**Comment by xavierfoucrier** [comment]
Hi @ebookpk,

@Sandstedt answer could work, but `mojs` can split animations in multiple DOM elements using `<div>`, so you can't export a whole timeline for example by just copy/paste the source output.

I don't think we will implement this kind of feature...

**Comment by ebookpk** [comment]
> Interesting question. I guess you could paus the animation at the time you wanna save as an SVG (example using mojs timeline), and then inspect the DOM in your browsers dev tools and copy the sourunding SVG DOM and save to a file.
@xavierfoucrier  @Sandstedt
thanks your reply ,
The below post said that svg document contain javascript code, so  how to using mojs timeline export javascript code ?
https://groups.google.com/forum/#!topic/snapsvg/BVTjd2PcmO0

**Comment by xavierfoucrier** [comment]
Hi @ebookpk,

Yeah SVG can contain javascript code... but `mojs` is using javascript **inside his core code structure**, not inside SVG. And as I said, there is not only SVG animated on the screen when using `mojs`.

**Comment by ebookpk** [comment]
@xavierfoucrier  Thank you very much!
