### ISSUE TITLE
"Running Locally" guide

### ISSUE THREAD

**Issue by processprocess** [mojs/mojs#251]
A guide for setting up and running the code locally would be awesome.

I would like to contribute however I'm running into issues installing and building the code.

**Comment by xavierfoucrier** [comment]
Hi @processprocess,

Thanks for opening the issue.

This is already done inside a "contributing" guide here:
https://github.com/mojs/mojs/blob/prepublish/CONTRIBUTING.md#working-with-the-project.

The guide will be merged soon with `v1.0.0` release :wink: 
I am closing the issue.

>  If you still run into issues when installing and building the library, please **contact us on the Slack workspace**. Join using the invite link here: https://github.com/mojs/mojs/tree/prepublish#developer.
