### ISSUE TITLE
可以为mojs添加一个removeShape的功能吗

### ISSUE THREAD

**Issue by rainydaycode** [mojs/mojs#257]
mojs.addShape( 'heart', Heart ); // passing name and Bubble class

我想 mojs.removeShape( 'heart' ); 

因为有的时候，添加的图形仅为了某一个模块使用，其他模块根本不会用到。我有一个比上面更好的提议是
(Because sometimes, the added graphics are only used by a certain module, and other modules are not used at all. I have a better proposal than the above)

class Heart extends mojs.CustomShape {} // 下面用到 (Used below)

const shape = new mojs.Shape({

  // Shape name. {String} [ 'circle' | 'rect' | 'polygon' | 'line' | 'cross' | 'equal' | 'curve' | 'zigzag' | '*custom defined name*' ]
  shape:            'circle', // 这里允许使用继承了mojs.CustomShape的类. e.g. shape: Heart (Classes that inherit mojs.CustomShape are allowed here. e.g. shape: Heart)
});

**Comment by rainydaycode** [comment]
mojs.addShape() 这个方法很令我困惑，因为我感觉它污染了全局环境。还是那个原因，有的时候我自定义的图形，仅会在某一个模块里用到，我不想这个图形是全局的。 This confuses me because I feel that I pollute the outside world. The same reason is that there are my customized graphics, which will only be in a certain module. I don't want this graphics to be my own.

**Comment by xavierfoucrier** [comment]
Hi @rainydaycode,

:warning: **You are on an open source community plateform**.

Please provide issue details and everything else **only in English**.
Without that, next issues will be closed the same way.

Thanks :+1:

**Comment by rainydaycode** [comment]
@xavierfoucrier Hmm, I will revise it tomorrow. Well, if you can, please close my issue.
