### ISSUE TITLE
Unable to import in "modules" mode

### ISSUE THREAD

**Issue by Armaldio** [mojs/mojs#259]
Hello, 

I'm starting with [vite](https://vitejs.dev/) but I'm unable to import `@mojs/core`
I investigate a bit and here's what I found:

Vite seems to look for the `package.json` `module` field, but after looking for it inside the `node_modules` folder, I can't find it
![image](https://user-images.githubusercontent.com/3089715/133607122-aa752306-c5e3-41f1-af33-f8c1c259c8a2.png)
![image](https://user-images.githubusercontent.com/3089715/133607155-0a0eec35-0b80-4b87-9bc1-3e93f6f0e4b2.png)

If I look inside the repo, that file is inside `./src/mojs.babel.js` while only `dist` is published to npm
![image](https://user-images.githubusercontent.com/3089715/133607294-95c6442f-02af-4ea2-857c-c77571b6edba.png)

Thanks!

**Comment by xavierfoucrier** [comment]
Hi @Armaldio,

Thanks for opening the issue.

As of today, there is no **ESM build** available inside the `dist` folder, **only UMD**.
This field is just here to "prepare" the next release, where we will provide an ESM version too.

I guess the only way to fix right now it to remove it.
Let me check and I get back to you as soon as possible.

Thanks! :wink:

**Comment by xavierfoucrier** [comment]
Hi @Armaldio,

I just published a new version on NPM.
You should be able to use it and get no errors, let me know if it's not the case.

Happy coding with mojs! :tada:

**Comment by Armaldio** [comment]
If works fine, many thanks!
