### ISSUE TITLE
Como corrigir o erro/How to fix the error: Uncaught TypeError: Cannot read properties of null (reading 'appendChild')

### ISSUE THREAD

**Issue by gomesgeovane** [mojs/mojs#261]
Como corrige esse erro?
How do you fix this error?

Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
at adicionar (script.js:27)
at HTMLInputElement.onclick (modelo.html:18)

OBS: Sou novo nesse mundo de Programação.
NOTE: I'm new to this programming world.

function adicionar() {
    if(isNumero(num.value) && !inLista(num.value, valores)) { //!inLista significa que o valor não está na lista.
        valores.push(Number(num.value))
        let item = document.createElement("option")
        item.text = `Valor ${num.value} adicionado.`
        **lista.appendChild(item)**  <-- O Inspecionar do Google está localizando isso/Google Inspect is finding this.
    } else {
        window.alert("Valor inválido ou já encontrado na lista.")
    }
}

**Comment by xavierfoucrier** [comment]
Hi @,

This issue is more related to **how your code is running** than mojs issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://github.com/mojs/mojs#developer.
