### ISSUE TITLE
Frame-by-frame animation

### ISSUE THREAD

**Issue by theproductiveprogrammer** [mojs/mojs#263]
I'm using mojs to animate a little bottle jumping into a box that then closes. Getting the bottle to jump into the box worked great using property curves but once it's in I need to replace the open box with frames that animate the box "closing". When I try this, the animation flickers badly.

This is a sample of what I've tried:
```javascript
    function close_box_1(step) {
      switch(step) {
        case 0:
          break;
        case 1:
          boxOpenFront.el.style.opacity=0
          boxHalfFront.play()
          boxOpenBack.el.style.opacity=0
          boxHalfBack.play()
          break;
        case 2:
          boxHalfFront.el.style.opacity=0
          boxHalfBack.el.style.opacity=0
          boxAlmostClosed.play()
          break;
        case 3:
          boxAlmostClosed.el.style.opacity=0
          boxClosed.play()
          break;
        default:
          return
      }
      setTimeout(() => close_box_1(step+1), 200)
    }
```

What is a better way to do frame by frame animation here? Any help would be greatly appreciated.

**Comment by Sandstedt** [comment]
Hmm, i think you should be able to do that with a then chain and the onComplete callback. Will see if I can throw together an example.

https://mojs.github.io/api/modules/html/#full-api-reference

**Comment by xavierfoucrier** [comment]
Hi all!

I agree with @Sandstedt, it's better to chain your animation and use the internal MoJS superpowers for that.

**Comment by theproductiveprogrammer** [comment]
I couldn't figure out how to chain the animation using MoJS but I did find the problem and solution. The problem seems to be that `Shape.play()` has a small delay and that causes a "white flash" between the frames. MoJS provides a `isSoftHide` attribute that handles this issue. Setting:
```js
    isSoftHide: false
```
in the `Shape`s allowed me to do this:
```js
    function close_box_1(step) {
      switch(step) {
        case 0:
          break;
        case 1:
          boxOpenFront.el.style.display="none"
          boxHalfFront.el.style.display="block"
          boxOpenBack.el.style.display="none"
          boxHalfBack.el.style.display="block"
          break;
        case 2:
          boxHalfFront.el.style.display="none"
          boxHalfBack.el.style.display="none"
          boxAlmostClosed.el.style.display="block"
          break;
        case 3:
          boxAlmostClosed.el.style.display="none"
          boxClosed.el.style.display="block"
          break;
        default:
          return
      }
      setTimeout(() => close_box_1(step+1), 200)
    }
```
And the animation is now smooth!

**Comment by Sandstedt** [comment]
Great you solved it @theproductiveprogrammer. Just a fast (not that beautiful) example what I meant with a then chain and also uses the timeline:
https://codepen.io/sandstedt/pen/oNGMJQp?editors=1111

But should of course not fade between the frames, but didn't have time to lab more with it for now. I guess yoy should use the `onStart` and `onRepeatComplete` callbacks. [Link to doc](https://mojs.github.io/api/tweens/tween.html)

**Comment by xavierfoucrier** [comment]
Agree (still) with @Sandstedt, it's better to use MoJS internal chaining instead of timeout.
Good luck and happy coding with MoJS.
> Nice demo BTW Jonas!

**Comment by theproductiveprogrammer** [comment]
> Just a fast (not that beautiful) example what I meant with a then chain and also uses the timeline:

@Sandstedt that's a really cool animation! Thanks a lot for for the code snippet - it's interesting and I'll play around with it 👍
