### ISSUE TITLE
Move Shape To Absolute Position

### ISSUE THREAD

**Issue by Miserlou** [mojs/mojs#266]
Hey all! Excellent project, looking forward to getting a lot of mileage out of this.

I've got what I think is a fairly straightforward question, but I haven't been able to piece together all of the bits yet.

When a button is clicked, I want to spawn a Shape and animate its location to another element on the page. Imagine clicking 'delete' on something and a little animation of a paper ball moving to a trash can at the bottom of the screen, for instance.

However, I don't see an example of this anywhere. I can spawn Shapes and move them around, but it seems to have trouble moving things to absolute positions. I can move to relative positions, but calculating the center of another object and then using that variable, like `x: {xCenter : e.pageX}` gives me `Expected color but found ‘xCenter’.  Error in parsing value for ‘color’.`, or `SyntaxError: missing : after property id`.

Is there a way to specify X and Y start/end locations as absolute positions on a page, not their relative positions to a parent element? Cheers!

**Comment by xavierfoucrier** [comment]
Hi @Miserlou,

This issue is more related to **how your code is running** than MoJS issue...

For this kind of question/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://github.com/mojs/mojs#developer.
