### ISSUE TITLE
The `dist` folder is missing in the npm package for `v1.7.0`

### ISSUE THREAD

**Issue by leonardoventurini** [mojs/mojs#275]
I downgraded to `v1.6.0` and it showed up fine. Not sure if it something wrong on my side, but it costs nothing to warn.

cc @xavierfoucrier

**Comment by xavierfoucrier** [comment]
@leonardoventurini 👋 

Woopsi! Good catch! 🔥 
I will publish a minor release soon to fix that.

Thanks for using mojs 🎉
