### ISSUE TITLE
What makes this library different from the rest!

### ISSUE THREAD

**Issue by Randore** [mojs/mojs#31]
Hi, if you could explain or write some description to show the differences between **mojs**
and other libraries that would be very useful to visitors and other developer who will be interest to work on Mojs (you know what I mean, you have already created demos with other frameworks).

**Comment by Charuru** [comment]
Yeah would like to hear some comments on popmotion, velocity, greensock.

**Comment by Sandstedt** [comment]
I would say that the larges differences is the Path Easing function that allow you to create complex easing and animation that are connected to each other. In GSAP there´s no build in function to define your own easing curves. (Havn't tried Popmotion or Velocity..)

**Comment by sdras** [comment]
That's not really true- GreenSock doesn't promote it that much, but MorphSVG plugin offers MorphSVGPlugin.pathDataToBezier(). I would say that the docs for this one feature in mo.js is pretty amazing. 

That function or anything like it does not currently live in Velocity, and likely won't as it seems not to be maintained anymore.

Does mo.js make it easier to work with sound, though? That might be something that sets it apart.

**Comment by karneaud** [comment]
I've been trying it out and must admit that its very micro easy and smooth on modern browsers. GreenSock is cool but I think its bulky and a lot of configuration stuff to go through for simple stuff. Moms seems easier to understand

**Comment by legomushroom** [comment]
Hi, guys!

I think `mojs` has very different intentions so it is hard to compare with the libraries, the web has nowadays. It does give you `tweens` and `timelines` but it also gives you other unique modules, for instance `"effect"` modules like `Shape` or `Burst`. These type of modules give you the ability to apply various effects to your sequences with just one declarative call. So it's like saying - `"Hey computer! I What a smoke current from this point!"` and the effect should appear. There are also other types of modules like that - the idea is to give you declarative `API` over some common animation problem. Furthermore, `mojs` is the `tooling-focusing` library thus will provide you with various tools to help you to craft your animation sequences and reduce pain overhead while working on them.

I think the every single aspect won't fit the issue format, so I will try to describe it with tutorials. I've written another 2 and will publish them as soon as I will find somebody to proofread them for me. I think these posts will put some light how is the `mojs` different with the current animation libraries and how it is similar. 

Hope it helps, sorry for so long reply. Cheers
