### ISSUE TITLE
Loading library gives `Uncaught TypeError: Cannot read property 'appendChild' of null`

### ISSUE THREAD

**Issue by suranyami** [mojs/mojs#32]
When loading `mo.js` I get this error:

``` javascript
Uncaught TypeError: Cannot read property 'appendChild' of null
```

on this line:

``` javascript
  Helpers.prototype.vars = function() {
    var ua;
    this.prefix = this.getPrefix();
    ...
    this.div = document.createElement('div');
    return document.body.appendChild(this.div);   <<<<<<< error here.
  };

What is the correct way to require/initalize this library?

I'm just trying to include it into a plain vanilla HTML page.
```

**Comment by legomushroom** [comment]
Hey @suranyami, sorry to hear that!

Please move the `script` link into the `body` (better to the end of the `body` tag).

Hope it helps.

**Comment by firefountain** [comment]
I'm having the same problem. Trying to get this working with angular.

**Comment by legomushroom** [comment]
@firefountain you are linking the library inside `body` tag?

**Comment by firefountain** [comment]
I'm trying to move the whole angular logic after that. Give me a few minutes

**Comment by firefountain** [comment]
@legomushroom if i move the whole thing to body it's working fine.

**Comment by legomushroom** [comment]
@firefountain ok cool, thanks for your feedback.

**Comment by legomushroom** [comment]
@firefountain that's because `mojs` use `body` tag as a fallback for `parent` option to place it's modules, thus if you link the library in `head` tag, the `body` isn't initialised yet and you get this error.

**Comment by Raminsiach** [comment]
Shouldnt though be a blocker when you have your javascript outside of body!

**Comment by Raminsiach** [comment]
Really cool job though. Congrats on this achievement!

**Comment by xavierfoucrier** [comment]
Hi @suranyami,

As described by @legomushroom, loading library into the document `<head>` is inappropriate if the library need to refer to the `<body>`...

I suggest you to move the `<script>` tag on the bottom of your document, or add a simple `DOMContentLoaded` event to check for the `<body>` availability, and load the library according to that.

Improving helpers in a next version should fix this issue.
Closing for now.
