### ISSUE TITLE
mojs.io links not working on mobile.

### ISSUE THREAD

**Issue by nikkop** [mojs/mojs#65]
Hi,
I'm not sure if this should be posted here but I'll give it a shot.

I have been trying several different links on the [mojs.io](http://mojs.io/) website and none of them work from a mobile phone. I have been trying both with a Android _(Chrome)_ and iPhone _(Chrome & Safari)_. Single touch or long touch, none works for targeting the links or opening them. 

When pressing the links in the **top menu**, it will simply **close**. When pressing a link in the **side menu**, the link will be **highlighted** (dot on the left side of the link) but nothing else will happen, it still stays open.

Currently, when I want to navigate around the website I have to go to github to find the links to the different sections or use Google to find the correct page.

Hope this can be fixed!

**Comment by Sandstedt** [comment]
It's a know problem. See: [https://github.com/legomushroom/mojs-website/issues/15](https://github.com/legomushroom/mojs-website/issues/15) 
If you want, you can send in a pull request to the mojs-website repo.

**Comment by legomushroom** [comment]
@nikkop sorry about that and thanks for the alert! It seem to break recently, we definitely need and will fix that. @nikkop, @Sandstedt please let me know guys if you are up for a PR!

Thanks!

// @Sandstedt
