### ISSUE TITLE
Could you please put examples code to github?

### ISSUE THREAD

**Issue by voronianski** [mojs/mojs#82]
It's almost impossible to read code in codepen...

**Comment by legomushroom** [comment]
Hi, Dmitri!

Thanks for the issue. Almost all demos are the Github, maybe some particular you are interested in?

- Animocons: [Demo](http://tympanus.net/Development/Animocons/) / [Repo](https://github.com/codrops/Animocons)
- Love or Hate Modal: [Demo](http://codepen.io/sol0mka/full/812699ce32c9a7aeb70c9384b32a533a/) / [Repo](https://github.com/legomushroom/shape-demo3)
- Mograph [Demo](http://codepen.io/sol0mka/full/39427561a8a0b15d7896480a7d96d3d1/) / [Repo](https://github.com/legomushroom/shape-demo3)
- Physical Balls [Demo](http://codepen.io/sol0mka/full/7315f4364360ec87a6655d33782702fe/) / [Repo](https://github.com/legomushroom/shape-demo2)

Some of the demos use deprecated syntax so I don't want to publish them to prevent confusion. Some of them a pretty simple and should be readable at CodePen.

Please let me know if you have any questions,
Cheers!

// @voronianski

**Comment by Journeytojah** [comment]
I just started using mojs, so I'm playing around with it.

You can find some basic stuff on my codepen [here](http://codepen.io/alexkidoo/pens/public/).

love the library and looking forward to working with it. maybe in the future when I am more confident I will make some tutorials :)

**Comment by legomushroom** [comment]
@Journeytojah hey, sorry about the difficulties. I will start working towards `mojs@1` release, planning to add lots of docs and invite you to participate :)

**Comment by Journeytojah** [comment]
@legomushroom Great! I already saw the timeline editor and I just want to congratulate you for the work you are doing. This is one hell of a tool for animations!

I will more than happy contribute in whatever way I can :)

**Comment by legomushroom** [comment]
@Journeytojah awesome! thanks a lot
