### ISSUE TITLE
Is it possible to change shape property of object after creation?

### ISSUE THREAD

**Issue by curranlipsett** [mojs/mojs#89]
I see the documentation says the .tune function can modify any property of the shape object, but can it change the actual shape of the object?

For example, would the following work:

```
var shape = new mojs.Shape({
    shape:      'circle',
    fill:       'red',
    radius:     '20',
});

// after some timeout or delay
shape.tune({shape: 'rect'});
```

I'm trying to loop through a few different images of birds to give it the look of flapping its wings and I'm not sure if it's possible to do with mojs.

**Comment by legomushroom** [comment]
Hi @curranlipsett! Thanks for the issue!

Nope, It's not possible, the `shape` probably is the only property you can't change right now.

**Comment by curranlipsett** [comment]
Thanks @legomushroom that makes sense to me. 

I appreciate the feedback!

**Comment by legomushroom** [comment]
@curranlipsett you are welcome, we are considering to make it `changeable` in the future but not sure about it yet.

**Comment by curranlipsett** [comment]
@legomushroom I could see the value in it, and it might be cool to see the transformation of the shapes as well. I think it is also possible to accomplish a pretty similar effect (at least in my case of trying to make it look like the bird is flapping wings) using path-easing like you have done with the mole example in the tutorial. 

It seems like it would be a lot of work to get this to work in all cases, especially if custom shapes are allowed.

**Comment by legomushroom** [comment]
@curranlipsett yeah it could be tricky, not just because custom shapes but also because shapes can have `deltable` parameters like `count` or `radius`/`radiusX/Y` that already can animate shapes. So this will become animation of shape morphing + shape's parameters animation which is tricky to do simultaneously.
